/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) dq_quadrotor_cost_ext_cost_e_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_norm_2 CASADI_PREFIX(norm_2)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_zeros CASADI_PREFIX(zeros)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

casadi_real casadi_norm_2(casadi_int n, const casadi_real* x) {
  return sqrt(casadi_dot(n, x, x));
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

static const casadi_int casadi_s0[3] = {14, 1, 1};
static const casadi_int casadi_s1[3] = {0, 1, 1};
static const casadi_int casadi_s2[3] = {50, 1, 1};
static const casadi_int casadi_s3[3] = {1, 1, 1};

static const casadi_real casadi_zeros[32] = 
  {0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.};

/* dq_quadrotor_cost_ext_cost_e_fun:(i0[14],i1[0],i2[0],i3[50])->(o0) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, w00, *w01=w+9, w02, *w03=w+18, *w04=w+21, w06, w07, w08, w09, *w10=w+51, w11;
  casadi_real w12, *w13=w+57, *w14=w+61, *w15=w+65, *w16=w+69, *w17=w+85, *w18=w+101, *w19=w+133, *w20=w+165, *w21=w+181, *w22=w+213, *w23=w+277;
  casadi_real w24, w25, w26, w27, w28, w29, w30, w31, *w32=w+349, *w33=w+363, *w34=w+371, *w35=w+374;
  casadi_real *w36=w+378, *w37=w+381, *w38=w+390, *w39=w+399;
  const casadi_real *cs, *ct, *wr05, *wr19, *wr34, *wr36;
  /* #0: @0 = 0 */
  w00 = 0.;
  /* #1: @1 = zeros(1x8) */
  casadi_clear(w01, 8);
  /* #2: @2 = 0.5 */
  w02 = 5.0000000000000000e-01;
  /* #3: @3 = all_2.22045e-16(3x1) */
  casadi_fill(w03, 3, 2.2204460492503131e-16);
  /* #4: @4 = zeros(8x1) */
  casadi_clear(w04, 8);
  /* #5: @5 = input[3][0] */
  wr05 = arg[3] ? arg[3] : casadi_zeros;
  /* #6: @6 = @5[0] */
  w06 = wr05[0];
  /* #7: @7 = @5[1] */
  w07 = wr05[1];
  /* #8: @8 = @5[2] */
  w08 = wr05[2];
  /* #9: @9 = @5[3] */
  w09 = wr05[3];
  /* #10: @10 = horzcat(@6, @7, @8, @9) */
  rr=w10;
  *rr++ = w06;
  *rr++ = w07;
  *rr++ = w08;
  *rr++ = w09;
  /* #11: @10 = @10' */
  /* #12: @11 = (-@7) */
  w11 = (- w07 );
  /* #13: @12 = (-@8) */
  w12 = (- w08 );
  /* #14: @13 = horzcat(@11, @6, @9, @12) */
  rr=w13;
  *rr++ = w11;
  *rr++ = w06;
  *rr++ = w09;
  *rr++ = w12;
  /* #15: @13 = @13' */
  /* #16: @9 = (-@9) */
  w09 = (- w09 );
  /* #17: @14 = horzcat(@12, @9, @6, @7) */
  rr=w14;
  *rr++ = w12;
  *rr++ = w09;
  *rr++ = w06;
  *rr++ = w07;
  /* #18: @14 = @14' */
  /* #19: @15 = horzcat(@9, @8, @11, @6) */
  rr=w15;
  *rr++ = w09;
  *rr++ = w08;
  *rr++ = w11;
  *rr++ = w06;
  /* #20: @15 = @15' */
  /* #21: @16 = horzcat(@10, @13, @14, @15) */
  rr=w16;
  for (i=0, cs=w10; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w13; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w14; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w15; i<4; ++i) *rr++ = *cs++;
  /* #22: @17 = @16' */
  for (i=0, rr=w17, cs=w16; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #23: @16 = zeros(4x4) */
  casadi_clear(w16, 16);
  /* #24: @18 = horzcat(@17, @16) */
  rr=w18;
  for (i=0, cs=w17; i<16; ++i) *rr++ = *cs++;
  for (i=0, cs=w16; i<16; ++i) *rr++ = *cs++;
  /* #25: @19 = @18' */
  for (i=0, rr=w19, cs=w18; i<8; ++i) for (j=0; j<4; ++j) rr[i+j*8] = *cs++;
  /* #26: @9 = @5[4] */
  w09 = wr05[4];
  /* #27: @8 = @5[5] */
  w08 = wr05[5];
  /* #28: @11 = @5[6] */
  w11 = wr05[6];
  /* #29: @6 = @5[7] */
  w06 = wr05[7];
  /* #30: @10 = horzcat(@9, @8, @11, @6) */
  rr=w10;
  *rr++ = w09;
  *rr++ = w08;
  *rr++ = w11;
  *rr++ = w06;
  /* #31: @10 = @10' */
  /* #32: @12 = (-@8) */
  w12 = (- w08 );
  /* #33: @7 = (-@11) */
  w07 = (- w11 );
  /* #34: @13 = horzcat(@12, @9, @6, @7) */
  rr=w13;
  *rr++ = w12;
  *rr++ = w09;
  *rr++ = w06;
  *rr++ = w07;
  /* #35: @13 = @13' */
  /* #36: @6 = (-@6) */
  w06 = (- w06 );
  /* #37: @14 = horzcat(@7, @6, @9, @8) */
  rr=w14;
  *rr++ = w07;
  *rr++ = w06;
  *rr++ = w09;
  *rr++ = w08;
  /* #38: @14 = @14' */
  /* #39: @15 = horzcat(@6, @11, @12, @9) */
  rr=w15;
  *rr++ = w06;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w09;
  /* #40: @15 = @15' */
  /* #41: @16 = horzcat(@10, @13, @14, @15) */
  rr=w16;
  for (i=0, cs=w10; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w13; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w14; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w15; i<4; ++i) *rr++ = *cs++;
  /* #42: @20 = @16' */
  for (i=0, rr=w20, cs=w16; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #43: @18 = horzcat(@20, @17) */
  rr=w18;
  for (i=0, cs=w20; i<16; ++i) *rr++ = *cs++;
  for (i=0, cs=w17; i<16; ++i) *rr++ = *cs++;
  /* #44: @21 = @18' */
  for (i=0, rr=w21, cs=w18; i<8; ++i) for (j=0; j<4; ++j) rr[i+j*8] = *cs++;
  /* #45: @22 = horzcat(@19, @21) */
  rr=w22;
  for (i=0, cs=w19; i<32; ++i) *rr++ = *cs++;
  for (i=0, cs=w21; i<32; ++i) *rr++ = *cs++;
  /* #46: @23 = @22' */
  for (i=0, rr=w23, cs=w22; i<8; ++i) for (j=0; j<8; ++j) rr[i+j*8] = *cs++;
  /* #47: @6 = input[0][0] */
  w06 = arg[0] ? arg[0][0] : 0;
  /* #48: @11 = input[0][1] */
  w11 = arg[0] ? arg[0][1] : 0;
  /* #49: @12 = input[0][2] */
  w12 = arg[0] ? arg[0][2] : 0;
  /* #50: @9 = input[0][3] */
  w09 = arg[0] ? arg[0][3] : 0;
  /* #51: @7 = input[0][4] */
  w07 = arg[0] ? arg[0][4] : 0;
  /* #52: @8 = input[0][5] */
  w08 = arg[0] ? arg[0][5] : 0;
  /* #53: @24 = input[0][6] */
  w24 = arg[0] ? arg[0][6] : 0;
  /* #54: @25 = input[0][7] */
  w25 = arg[0] ? arg[0][7] : 0;
  /* #55: @26 = input[0][8] */
  w26 = arg[0] ? arg[0][8] : 0;
  /* #56: @27 = input[0][9] */
  w27 = arg[0] ? arg[0][9] : 0;
  /* #57: @28 = input[0][10] */
  w28 = arg[0] ? arg[0][10] : 0;
  /* #58: @29 = input[0][11] */
  w29 = arg[0] ? arg[0][11] : 0;
  /* #59: @30 = input[0][12] */
  w30 = arg[0] ? arg[0][12] : 0;
  /* #60: @31 = input[0][13] */
  w31 = arg[0] ? arg[0][13] : 0;
  /* #61: @32 = vertcat(@6, @11, @12, @9, @7, @8, @24, @25, @26, @27, @28, @29, @30, @31) */
  rr=w32;
  *rr++ = w06;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w09;
  *rr++ = w07;
  *rr++ = w08;
  *rr++ = w24;
  *rr++ = w25;
  *rr++ = w26;
  *rr++ = w27;
  *rr++ = w28;
  *rr++ = w29;
  *rr++ = w30;
  *rr++ = w31;
  /* #62: @33 = @32[:8] */
  for (rr=w33, cs=w32+0; cs!=w32+8; cs+=1) *rr++ = *cs;
  /* #63: @4 = mac(@23,@33,@4) */
  for (i=0, rr=w04; i<1; ++i) for (j=0; j<8; ++j, ++rr) for (k=0, cs=w23+j, ct=w33+i*8; k<8; ++k) *rr += cs[k*8]**ct++;
  /* #64: @34 = @4[1:4] */
  for (rr=w34, cs=w04+1; cs!=w04+4; cs+=1) *rr++ = *cs;
  /* #65: @3 = (@3+@34) */
  for (i=0, rr=w03, cs=w34; i<3; ++i) (*rr++) += (*cs++);
  /* #66: @6 = ||@3||_F */
  w06 = casadi_norm_2(3, w03);
  /* #67: @11 = @4[0] */
  for (rr=(&w11), cs=w04+0; cs!=w04+1; cs+=1) *rr++ = *cs;
  /* #68: @12 = atan2(@6,@11) */
  w12  = atan2(w06,w11);
  /* #69: @12 = (2.*@12) */
  w12 = (2.* w12 );
  /* #70: @12 = (@2*@12) */
  w12  = (w02*w12);
  /* #71: @9 = @4[1] */
  for (rr=(&w09), cs=w04+1; cs!=w04+2; cs+=1) *rr++ = *cs;
  /* #72: @7 = (@12*@9) */
  w07  = (w12*w09);
  /* #73: @7 = (@7/@6) */
  w07 /= w06;
  /* #74: @8 = @4[2] */
  for (rr=(&w08), cs=w04+2; cs!=w04+3; cs+=1) *rr++ = *cs;
  /* #75: @24 = (@12*@8) */
  w24  = (w12*w08);
  /* #76: @24 = (@24/@6) */
  w24 /= w06;
  /* #77: @25 = @4[3] */
  for (rr=(&w25), cs=w04+3; cs!=w04+4; cs+=1) *rr++ = *cs;
  /* #78: @12 = (@12*@25) */
  w12 *= w25;
  /* #79: @12 = (@12/@6) */
  w12 /= w06;
  /* #80: @10 = zeros(4x1) */
  casadi_clear(w10, 4);
  /* #81: @6 = @4[4] */
  for (rr=(&w06), cs=w04+4; cs!=w04+5; cs+=1) *rr++ = *cs;
  /* #82: @26 = @4[5] */
  for (rr=(&w26), cs=w04+5; cs!=w04+6; cs+=1) *rr++ = *cs;
  /* #83: @27 = (-@26) */
  w27 = (- w26 );
  /* #84: @28 = @4[6] */
  for (rr=(&w28), cs=w04+6; cs!=w04+7; cs+=1) *rr++ = *cs;
  /* #85: @29 = (-@28) */
  w29 = (- w28 );
  /* #86: @30 = @4[7] */
  for (rr=(&w30), cs=w04+7; cs!=w04+8; cs+=1) *rr++ = *cs;
  /* #87: @31 = (-@30) */
  w31 = (- w30 );
  /* #88: @13 = horzcat(@6, @27, @29, @31) */
  rr=w13;
  *rr++ = w06;
  *rr++ = w27;
  *rr++ = w29;
  *rr++ = w31;
  /* #89: @13 = @13' */
  /* #90: @14 = horzcat(@26, @6, @31, @28) */
  rr=w14;
  *rr++ = w26;
  *rr++ = w06;
  *rr++ = w31;
  *rr++ = w28;
  /* #91: @14 = @14' */
  /* #92: @15 = horzcat(@28, @30, @6, @27) */
  rr=w15;
  *rr++ = w28;
  *rr++ = w30;
  *rr++ = w06;
  *rr++ = w27;
  /* #93: @15 = @15' */
  /* #94: @35 = horzcat(@30, @29, @26, @6) */
  rr=w35;
  *rr++ = w30;
  *rr++ = w29;
  *rr++ = w26;
  *rr++ = w06;
  /* #95: @35 = @35' */
  /* #96: @20 = horzcat(@13, @14, @15, @35) */
  rr=w20;
  for (i=0, cs=w13; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w14; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w15; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w35; i<4; ++i) *rr++ = *cs++;
  /* #97: @17 = @20' */
  for (i=0, rr=w17, cs=w20; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #98: @17 = (2.*@17) */
  for (i=0, rr=w17, cs=w17; i<16; ++i) *rr++ = (2.* *cs++ );
  /* #99: @9 = (-@9) */
  w09 = (- w09 );
  /* #100: @8 = (-@8) */
  w08 = (- w08 );
  /* #101: @25 = (-@25) */
  w25 = (- w25 );
  /* #102: @13 = vertcat(@11, @9, @8, @25) */
  rr=w13;
  *rr++ = w11;
  *rr++ = w09;
  *rr++ = w08;
  *rr++ = w25;
  /* #103: @10 = mac(@17,@13,@10) */
  for (i=0, rr=w10; i<1; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, cs=w17+j, ct=w13+i*4; k<4; ++k) *rr += cs[k*4]**ct++;
  /* #104: @11 = @10[1] */
  for (rr=(&w11), cs=w10+1; cs!=w10+2; cs+=1) *rr++ = *cs;
  /* #105: @11 = (@2*@11) */
  w11  = (w02*w11);
  /* #106: @9 = @10[2] */
  for (rr=(&w09), cs=w10+2; cs!=w10+3; cs+=1) *rr++ = *cs;
  /* #107: @9 = (@2*@9) */
  w09  = (w02*w09);
  /* #108: @8 = @10[3] */
  for (rr=(&w08), cs=w10+3; cs!=w10+4; cs+=1) *rr++ = *cs;
  /* #109: @2 = (@2*@8) */
  w02 *= w08;
  /* #110: @4 = vertcat(@0, @7, @24, @12, @0, @11, @9, @2) */
  rr=w04;
  *rr++ = w00;
  *rr++ = w07;
  *rr++ = w24;
  *rr++ = w12;
  *rr++ = w00;
  *rr++ = w11;
  *rr++ = w09;
  *rr++ = w02;
  /* #111: @33 = @4' */
  casadi_copy(w04, 8, w33);
  /* #112: @23 = zeros(8x8) */
  casadi_clear(w23, 64);
  /* #113: @19 = input[3][1] */
  wr19 = arg[3] ? arg[3]+18 : casadi_zeros;
  /* #114: @7 = @19[7] */
  w07 = wr19[7];
  /* #115: (@23[0] = @7) */
  for (rr=w23+0, cs=(&w07); rr!=w23+1; rr+=1) *rr = *cs++;
  /* #116: @7 = @19[8] */
  w07 = wr19[8];
  /* #117: (@23[9] = @7) */
  for (rr=w23+9, cs=(&w07); rr!=w23+10; rr+=1) *rr = *cs++;
  /* #118: @7 = @19[9] */
  w07 = wr19[9];
  /* #119: (@23[18] = @7) */
  for (rr=w23+18, cs=(&w07); rr!=w23+19; rr+=1) *rr = *cs++;
  /* #120: @7 = @19[10] */
  w07 = wr19[10];
  /* #121: (@23[27] = @7) */
  for (rr=w23+27, cs=(&w07); rr!=w23+28; rr+=1) *rr = *cs++;
  /* #122: @7 = @19[0] */
  w07 = wr19[0];
  /* #123: (@23[36] = @7) */
  for (rr=w23+36, cs=(&w07); rr!=w23+37; rr+=1) *rr = *cs++;
  /* #124: @7 = @19[1] */
  w07 = wr19[1];
  /* #125: (@23[45] = @7) */
  for (rr=w23+45, cs=(&w07); rr!=w23+46; rr+=1) *rr = *cs++;
  /* #126: @7 = @19[2] */
  w07 = wr19[2];
  /* #127: (@23[54] = @7) */
  for (rr=w23+54, cs=(&w07); rr!=w23+55; rr+=1) *rr = *cs++;
  /* #128: @7 = @19[3] */
  w07 = wr19[3];
  /* #129: (@23[63] = @7) */
  for (rr=w23+63, cs=(&w07); rr!=w23+64; rr+=1) *rr = *cs++;
  /* #130: @1 = mac(@33,@23,@1) */
  for (i=0, rr=w01; i<8; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w33+j, ct=w23+i*8; k<8; ++k) *rr += cs[k*1]**ct++;
  /* #131: @7 = mac(@1,@4,@0) */
  casadi_copy((&w00), 1, (&w07));
  for (i=0, rr=(&w07); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w01+j, ct=w04+i*8; k<8; ++k) *rr += cs[k*1]**ct++;
  /* #132: @3 = zeros(1x3) */
  casadi_clear(w03, 3);
  /* #133: @34 = @32[11:14] */
  for (rr=w34, cs=w32+11; cs!=w32+14; cs+=1) *rr++ = *cs;
  /* #134: @36 = @5[11:14] */
  wr36 = wr05+11;
  /* #135: @34 = (@34-@36) */
  for (i=0, rr=w34, cs=wr36; i<3; ++i) (*rr++) -= (*cs++);
  /* #136: @36 = @34' */
  casadi_copy(w34, 3, w36);
  /* #137: @37 = zeros(3x3) */
  casadi_clear(w37, 9);
  /* #138: @24 = @19[4] */
  w24 = wr19[4];
  /* #139: @38 = @37; (@38[0] = @24) */
  casadi_copy(w37, 9, w38);
  for (rr=w38+0, cs=(&w24); rr!=w38+1; rr+=1) *rr = *cs++;
  /* #140: @24 = @19[5] */
  w24 = wr19[5];
  /* #141: (@38[4] = @24) */
  for (rr=w38+4, cs=(&w24); rr!=w38+5; rr+=1) *rr = *cs++;
  /* #142: @24 = @19[6] */
  w24 = wr19[6];
  /* #143: (@38[8] = @24) */
  for (rr=w38+8, cs=(&w24); rr!=w38+9; rr+=1) *rr = *cs++;
  /* #144: @39 = mac(@36,@38,@3) */
  casadi_copy(w03, 3, w39);
  for (i=0, rr=w39; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w36+j, ct=w38+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #145: @24 = mac(@39,@34,@0) */
  casadi_copy((&w00), 1, (&w24));
  for (i=0, rr=(&w24); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w39+j, ct=w34+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #146: @7 = (@7+@24) */
  w07 += w24;
  /* #147: @39 = @32[8:11] */
  for (rr=w39, cs=w32+8; cs!=w32+11; cs+=1) *rr++ = *cs;
  /* #148: @34 = @5[8:11] */
  wr34 = wr05+8;
  /* #149: @39 = (@39-@34) */
  for (i=0, rr=w39, cs=wr34; i<3; ++i) (*rr++) -= (*cs++);
  /* #150: @34 = @39' */
  casadi_copy(w39, 3, w34);
  /* #151: @24 = @19[11] */
  w24 = wr19[11];
  /* #152: (@37[0] = @24) */
  for (rr=w37+0, cs=(&w24); rr!=w37+1; rr+=1) *rr = *cs++;
  /* #153: @24 = @19[12] */
  w24 = wr19[12];
  /* #154: (@37[4] = @24) */
  for (rr=w37+4, cs=(&w24); rr!=w37+5; rr+=1) *rr = *cs++;
  /* #155: @24 = @19[13] */
  w24 = wr19[13];
  /* #156: (@37[8] = @24) */
  for (rr=w37+8, cs=(&w24); rr!=w37+9; rr+=1) *rr = *cs++;
  /* #157: @3 = mac(@34,@37,@3) */
  for (i=0, rr=w03; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w34+j, ct=w37+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #158: @0 = mac(@3,@39,@0) */
  for (i=0, rr=(&w00); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w03+j, ct=w39+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #159: @7 = (@7+@0) */
  w07 += w00;
  /* #160: output[0][0] = @7 */
  if (res[0]) res[0][0] = w07;
  return 0;
}

CASADI_SYMBOL_EXPORT int dq_quadrotor_cost_ext_cost_e_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int dq_quadrotor_cost_ext_cost_e_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int dq_quadrotor_cost_ext_cost_e_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void dq_quadrotor_cost_ext_cost_e_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int dq_quadrotor_cost_ext_cost_e_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void dq_quadrotor_cost_ext_cost_e_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void dq_quadrotor_cost_ext_cost_e_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void dq_quadrotor_cost_ext_cost_e_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int dq_quadrotor_cost_ext_cost_e_fun_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int dq_quadrotor_cost_ext_cost_e_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real dq_quadrotor_cost_ext_cost_e_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* dq_quadrotor_cost_ext_cost_e_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* dq_quadrotor_cost_ext_cost_e_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* dq_quadrotor_cost_ext_cost_e_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* dq_quadrotor_cost_ext_cost_e_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int dq_quadrotor_cost_ext_cost_e_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 18;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 402;
  return 0;
}

CASADI_SYMBOL_EXPORT int dq_quadrotor_cost_ext_cost_e_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 18*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 402*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
