/* This file was automatically generated by CasADi 3.6.4.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) dq_quadrotor_cost_ext_cost_e_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

static const casadi_int casadi_s0[18] = {14, 1, 0, 14, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13};
static const casadi_int casadi_s1[4] = {0, 1, 0, 0};
static const casadi_int casadi_s2[54] = {50, 1, 0, 50, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49};
static const casadi_int casadi_s3[5] = {1, 1, 0, 1, 0};

/* dq_quadrotor_cost_ext_cost_e_fun:(i0[14],i1[0],i2[0],i3[50])->(o0) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *ss, *tt;
  const casadi_real *cs;
  casadi_real w0, *w1=w+9, w2, *w3=w+18, *w4=w+21, *w5=w+29, w6, w7, w8, w9, *w10=w+51, w11, w12, *w13=w+57, *w14=w+61, *w15=w+65, *w16=w+69, *w17=w+85, *w18=w+101, *w19=w+133, *w20=w+165, *w21=w+181, *w22=w+213, *w23=w+277, w24, w25, w26, w27, w28, w29, w30, w31, *w32=w+349, *w33=w+363, *w34=w+371, *w35=w+374, *w36=w+378, *w37=w+381, *w38=w+390, *w39=w+399;
  /* #0: @0 = 0 */
  w0 = 0.;
  /* #1: @1 = zeros(1x8) */
  casadi_clear(w1, 8);
  /* #2: @2 = 0.5 */
  w2 = 5.0000000000000000e-01;
  /* #3: @3 = all_2.22045e-16(3x1) */
  casadi_fill(w3, 3, 2.2204460492503131e-16);
  /* #4: @4 = zeros(8x1) */
  casadi_clear(w4, 8);
  /* #5: @5 = input[3][0] */
  casadi_copy(arg[3], 18, w5);
  /* #6: @6 = @5[0] */
  for (rr=(&w6), ss=w5+0; ss!=w5+1; ss+=1) *rr++ = *ss;
  /* #7: @7 = @5[1] */
  for (rr=(&w7), ss=w5+1; ss!=w5+2; ss+=1) *rr++ = *ss;
  /* #8: @8 = @5[2] */
  for (rr=(&w8), ss=w5+2; ss!=w5+3; ss+=1) *rr++ = *ss;
  /* #9: @9 = @5[3] */
  for (rr=(&w9), ss=w5+3; ss!=w5+4; ss+=1) *rr++ = *ss;
  /* #10: @10 = horzcat(@6, @7, @8, @9) */
  rr=w10;
  *rr++ = w6;
  *rr++ = w7;
  *rr++ = w8;
  *rr++ = w9;
  /* #11: @10 = @10' */
  /* #12: @11 = (-@7) */
  w11 = (- w7 );
  /* #13: @12 = (-@8) */
  w12 = (- w8 );
  /* #14: @13 = horzcat(@11, @6, @9, @12) */
  rr=w13;
  *rr++ = w11;
  *rr++ = w6;
  *rr++ = w9;
  *rr++ = w12;
  /* #15: @13 = @13' */
  /* #16: @9 = (-@9) */
  w9 = (- w9 );
  /* #17: @14 = horzcat(@12, @9, @6, @7) */
  rr=w14;
  *rr++ = w12;
  *rr++ = w9;
  *rr++ = w6;
  *rr++ = w7;
  /* #18: @14 = @14' */
  /* #19: @15 = horzcat(@9, @8, @11, @6) */
  rr=w15;
  *rr++ = w9;
  *rr++ = w8;
  *rr++ = w11;
  *rr++ = w6;
  /* #20: @15 = @15' */
  /* #21: @16 = horzcat(@10, @13, @14, @15) */
  rr=w16;
  for (i=0, cs=w10; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w13; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w14; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w15; i<4; ++i) *rr++ = *cs++;
  /* #22: @17 = @16' */
  for (i=0, rr=w17, cs=w16; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #23: @16 = zeros(4x4) */
  casadi_clear(w16, 16);
  /* #24: @18 = horzcat(@17, @16) */
  rr=w18;
  for (i=0, cs=w17; i<16; ++i) *rr++ = *cs++;
  for (i=0, cs=w16; i<16; ++i) *rr++ = *cs++;
  /* #25: @19 = @18' */
  for (i=0, rr=w19, cs=w18; i<8; ++i) for (j=0; j<4; ++j) rr[i+j*8] = *cs++;
  /* #26: @9 = @5[4] */
  for (rr=(&w9), ss=w5+4; ss!=w5+5; ss+=1) *rr++ = *ss;
  /* #27: @8 = @5[5] */
  for (rr=(&w8), ss=w5+5; ss!=w5+6; ss+=1) *rr++ = *ss;
  /* #28: @11 = @5[6] */
  for (rr=(&w11), ss=w5+6; ss!=w5+7; ss+=1) *rr++ = *ss;
  /* #29: @6 = @5[7] */
  for (rr=(&w6), ss=w5+7; ss!=w5+8; ss+=1) *rr++ = *ss;
  /* #30: @10 = horzcat(@9, @8, @11, @6) */
  rr=w10;
  *rr++ = w9;
  *rr++ = w8;
  *rr++ = w11;
  *rr++ = w6;
  /* #31: @10 = @10' */
  /* #32: @12 = (-@8) */
  w12 = (- w8 );
  /* #33: @7 = (-@11) */
  w7 = (- w11 );
  /* #34: @13 = horzcat(@12, @9, @6, @7) */
  rr=w13;
  *rr++ = w12;
  *rr++ = w9;
  *rr++ = w6;
  *rr++ = w7;
  /* #35: @13 = @13' */
  /* #36: @6 = (-@6) */
  w6 = (- w6 );
  /* #37: @14 = horzcat(@7, @6, @9, @8) */
  rr=w14;
  *rr++ = w7;
  *rr++ = w6;
  *rr++ = w9;
  *rr++ = w8;
  /* #38: @14 = @14' */
  /* #39: @15 = horzcat(@6, @11, @12, @9) */
  rr=w15;
  *rr++ = w6;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w9;
  /* #40: @15 = @15' */
  /* #41: @16 = horzcat(@10, @13, @14, @15) */
  rr=w16;
  for (i=0, cs=w10; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w13; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w14; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w15; i<4; ++i) *rr++ = *cs++;
  /* #42: @20 = @16' */
  for (i=0, rr=w20, cs=w16; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #43: @18 = horzcat(@20, @17) */
  rr=w18;
  for (i=0, cs=w20; i<16; ++i) *rr++ = *cs++;
  for (i=0, cs=w17; i<16; ++i) *rr++ = *cs++;
  /* #44: @21 = @18' */
  for (i=0, rr=w21, cs=w18; i<8; ++i) for (j=0; j<4; ++j) rr[i+j*8] = *cs++;
  /* #45: @22 = horzcat(@19, @21) */
  rr=w22;
  for (i=0, cs=w19; i<32; ++i) *rr++ = *cs++;
  for (i=0, cs=w21; i<32; ++i) *rr++ = *cs++;
  /* #46: @23 = @22' */
  for (i=0, rr=w23, cs=w22; i<8; ++i) for (j=0; j<8; ++j) rr[i+j*8] = *cs++;
  /* #47: @6 = input[0][0] */
  w6 = arg[0] ? arg[0][0] : 0;
  /* #48: @11 = input[0][1] */
  w11 = arg[0] ? arg[0][1] : 0;
  /* #49: @12 = input[0][2] */
  w12 = arg[0] ? arg[0][2] : 0;
  /* #50: @9 = input[0][3] */
  w9 = arg[0] ? arg[0][3] : 0;
  /* #51: @7 = input[0][4] */
  w7 = arg[0] ? arg[0][4] : 0;
  /* #52: @8 = input[0][5] */
  w8 = arg[0] ? arg[0][5] : 0;
  /* #53: @24 = input[0][6] */
  w24 = arg[0] ? arg[0][6] : 0;
  /* #54: @25 = input[0][7] */
  w25 = arg[0] ? arg[0][7] : 0;
  /* #55: @26 = input[0][8] */
  w26 = arg[0] ? arg[0][8] : 0;
  /* #56: @27 = input[0][9] */
  w27 = arg[0] ? arg[0][9] : 0;
  /* #57: @28 = input[0][10] */
  w28 = arg[0] ? arg[0][10] : 0;
  /* #58: @29 = input[0][11] */
  w29 = arg[0] ? arg[0][11] : 0;
  /* #59: @30 = input[0][12] */
  w30 = arg[0] ? arg[0][12] : 0;
  /* #60: @31 = input[0][13] */
  w31 = arg[0] ? arg[0][13] : 0;
  /* #61: @32 = vertcat(@6, @11, @12, @9, @7, @8, @24, @25, @26, @27, @28, @29, @30, @31) */
  rr=w32;
  *rr++ = w6;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w9;
  *rr++ = w7;
  *rr++ = w8;
  *rr++ = w24;
  *rr++ = w25;
  *rr++ = w26;
  *rr++ = w27;
  *rr++ = w28;
  *rr++ = w29;
  *rr++ = w30;
  *rr++ = w31;
  /* #62: @33 = @32[:8] */
  for (rr=w33, ss=w32+0; ss!=w32+8; ss+=1) *rr++ = *ss;
  /* #63: @4 = mac(@23,@33,@4) */
  for (i=0, rr=w4; i<1; ++i) for (j=0; j<8; ++j, ++rr) for (k=0, ss=w23+j, tt=w33+i*8; k<8; ++k) *rr += ss[k*8]**tt++;
  /* #64: @34 = @4[1:4] */
  for (rr=w34, ss=w4+1; ss!=w4+4; ss+=1) *rr++ = *ss;
  /* #65: @3 = (@3+@34) */
  for (i=0, rr=w3, cs=w34; i<3; ++i) (*rr++) += (*cs++);
  /* #66: @6 = ||@3||_F */
  w6 = sqrt(casadi_dot(3, w3, w3));
  /* #67: @11 = @4[0] */
  for (rr=(&w11), ss=w4+0; ss!=w4+1; ss+=1) *rr++ = *ss;
  /* #68: @12 = atan2(@6,@11) */
  w12  = atan2(w6,w11);
  /* #69: @12 = (2.*@12) */
  w12 = (2.* w12 );
  /* #70: @12 = (@2*@12) */
  w12  = (w2*w12);
  /* #71: @9 = @4[1] */
  for (rr=(&w9), ss=w4+1; ss!=w4+2; ss+=1) *rr++ = *ss;
  /* #72: @7 = (@12*@9) */
  w7  = (w12*w9);
  /* #73: @7 = (@7/@6) */
  w7 /= w6;
  /* #74: @8 = @4[2] */
  for (rr=(&w8), ss=w4+2; ss!=w4+3; ss+=1) *rr++ = *ss;
  /* #75: @24 = (@12*@8) */
  w24  = (w12*w8);
  /* #76: @24 = (@24/@6) */
  w24 /= w6;
  /* #77: @25 = @4[3] */
  for (rr=(&w25), ss=w4+3; ss!=w4+4; ss+=1) *rr++ = *ss;
  /* #78: @12 = (@12*@25) */
  w12 *= w25;
  /* #79: @12 = (@12/@6) */
  w12 /= w6;
  /* #80: @10 = zeros(4x1) */
  casadi_clear(w10, 4);
  /* #81: @6 = @4[4] */
  for (rr=(&w6), ss=w4+4; ss!=w4+5; ss+=1) *rr++ = *ss;
  /* #82: @26 = @4[5] */
  for (rr=(&w26), ss=w4+5; ss!=w4+6; ss+=1) *rr++ = *ss;
  /* #83: @27 = (-@26) */
  w27 = (- w26 );
  /* #84: @28 = @4[6] */
  for (rr=(&w28), ss=w4+6; ss!=w4+7; ss+=1) *rr++ = *ss;
  /* #85: @29 = (-@28) */
  w29 = (- w28 );
  /* #86: @30 = @4[7] */
  for (rr=(&w30), ss=w4+7; ss!=w4+8; ss+=1) *rr++ = *ss;
  /* #87: @31 = (-@30) */
  w31 = (- w30 );
  /* #88: @13 = horzcat(@6, @27, @29, @31) */
  rr=w13;
  *rr++ = w6;
  *rr++ = w27;
  *rr++ = w29;
  *rr++ = w31;
  /* #89: @13 = @13' */
  /* #90: @14 = horzcat(@26, @6, @31, @28) */
  rr=w14;
  *rr++ = w26;
  *rr++ = w6;
  *rr++ = w31;
  *rr++ = w28;
  /* #91: @14 = @14' */
  /* #92: @15 = horzcat(@28, @30, @6, @27) */
  rr=w15;
  *rr++ = w28;
  *rr++ = w30;
  *rr++ = w6;
  *rr++ = w27;
  /* #93: @15 = @15' */
  /* #94: @35 = horzcat(@30, @29, @26, @6) */
  rr=w35;
  *rr++ = w30;
  *rr++ = w29;
  *rr++ = w26;
  *rr++ = w6;
  /* #95: @35 = @35' */
  /* #96: @20 = horzcat(@13, @14, @15, @35) */
  rr=w20;
  for (i=0, cs=w13; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w14; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w15; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w35; i<4; ++i) *rr++ = *cs++;
  /* #97: @17 = @20' */
  for (i=0, rr=w17, cs=w20; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #98: @17 = (2.*@17) */
  for (i=0, rr=w17, cs=w17; i<16; ++i) *rr++ = (2.* *cs++ );
  /* #99: @9 = (-@9) */
  w9 = (- w9 );
  /* #100: @8 = (-@8) */
  w8 = (- w8 );
  /* #101: @25 = (-@25) */
  w25 = (- w25 );
  /* #102: @13 = vertcat(@11, @9, @8, @25) */
  rr=w13;
  *rr++ = w11;
  *rr++ = w9;
  *rr++ = w8;
  *rr++ = w25;
  /* #103: @10 = mac(@17,@13,@10) */
  for (i=0, rr=w10; i<1; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w17+j, tt=w13+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #104: @11 = @10[1] */
  for (rr=(&w11), ss=w10+1; ss!=w10+2; ss+=1) *rr++ = *ss;
  /* #105: @11 = (@2*@11) */
  w11  = (w2*w11);
  /* #106: @9 = @10[2] */
  for (rr=(&w9), ss=w10+2; ss!=w10+3; ss+=1) *rr++ = *ss;
  /* #107: @9 = (@2*@9) */
  w9  = (w2*w9);
  /* #108: @8 = @10[3] */
  for (rr=(&w8), ss=w10+3; ss!=w10+4; ss+=1) *rr++ = *ss;
  /* #109: @2 = (@2*@8) */
  w2 *= w8;
  /* #110: @4 = vertcat(@0, @7, @24, @12, @0, @11, @9, @2) */
  rr=w4;
  *rr++ = w0;
  *rr++ = w7;
  *rr++ = w24;
  *rr++ = w12;
  *rr++ = w0;
  *rr++ = w11;
  *rr++ = w9;
  *rr++ = w2;
  /* #111: @33 = @4' */
  casadi_copy(w4, 8, w33);
  /* #112: @23 = zeros(8x8) */
  casadi_clear(w23, 64);
  /* #113: @19 = input[3][1] */
  casadi_copy(arg[3] ? arg[3]+18 : 0, 32, w19);
  /* #114: @7 = @19[7] */
  for (rr=(&w7), ss=w19+7; ss!=w19+8; ss+=1) *rr++ = *ss;
  /* #115: (@23[0] = @7) */
  for (rr=w23+0, ss=(&w7); rr!=w23+1; rr+=1) *rr = *ss++;
  /* #116: @7 = @19[8] */
  for (rr=(&w7), ss=w19+8; ss!=w19+9; ss+=1) *rr++ = *ss;
  /* #117: (@23[9] = @7) */
  for (rr=w23+9, ss=(&w7); rr!=w23+10; rr+=1) *rr = *ss++;
  /* #118: @7 = @19[9] */
  for (rr=(&w7), ss=w19+9; ss!=w19+10; ss+=1) *rr++ = *ss;
  /* #119: (@23[18] = @7) */
  for (rr=w23+18, ss=(&w7); rr!=w23+19; rr+=1) *rr = *ss++;
  /* #120: @7 = @19[10] */
  for (rr=(&w7), ss=w19+10; ss!=w19+11; ss+=1) *rr++ = *ss;
  /* #121: (@23[27] = @7) */
  for (rr=w23+27, ss=(&w7); rr!=w23+28; rr+=1) *rr = *ss++;
  /* #122: @7 = @19[0] */
  for (rr=(&w7), ss=w19+0; ss!=w19+1; ss+=1) *rr++ = *ss;
  /* #123: (@23[36] = @7) */
  for (rr=w23+36, ss=(&w7); rr!=w23+37; rr+=1) *rr = *ss++;
  /* #124: @7 = @19[1] */
  for (rr=(&w7), ss=w19+1; ss!=w19+2; ss+=1) *rr++ = *ss;
  /* #125: (@23[45] = @7) */
  for (rr=w23+45, ss=(&w7); rr!=w23+46; rr+=1) *rr = *ss++;
  /* #126: @7 = @19[2] */
  for (rr=(&w7), ss=w19+2; ss!=w19+3; ss+=1) *rr++ = *ss;
  /* #127: (@23[54] = @7) */
  for (rr=w23+54, ss=(&w7); rr!=w23+55; rr+=1) *rr = *ss++;
  /* #128: @7 = @19[3] */
  for (rr=(&w7), ss=w19+3; ss!=w19+4; ss+=1) *rr++ = *ss;
  /* #129: (@23[63] = @7) */
  for (rr=w23+63, ss=(&w7); rr!=w23+64; rr+=1) *rr = *ss++;
  /* #130: @1 = mac(@33,@23,@1) */
  for (i=0, rr=w1; i<8; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w33+j, tt=w23+i*8; k<8; ++k) *rr += ss[k*1]**tt++;
  /* #131: @7 = mac(@1,@4,@0) */
  casadi_copy((&w0), 1, (&w7));
  for (i=0, rr=(&w7); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w1+j, tt=w4+i*8; k<8; ++k) *rr += ss[k*1]**tt++;
  /* #132: @3 = zeros(1x3) */
  casadi_clear(w3, 3);
  /* #133: @34 = @32[11:14] */
  for (rr=w34, ss=w32+11; ss!=w32+14; ss+=1) *rr++ = *ss;
  /* #134: @36 = @5[11:14] */
  for (rr=w36, ss=w5+11; ss!=w5+14; ss+=1) *rr++ = *ss;
  /* #135: @34 = (@34-@36) */
  for (i=0, rr=w34, cs=w36; i<3; ++i) (*rr++) -= (*cs++);
  /* #136: @36 = @34' */
  casadi_copy(w34, 3, w36);
  /* #137: @37 = zeros(3x3) */
  casadi_clear(w37, 9);
  /* #138: @24 = @19[4] */
  for (rr=(&w24), ss=w19+4; ss!=w19+5; ss+=1) *rr++ = *ss;
  /* #139: @38 = @37; (@38[0] = @24) */
  casadi_copy(w37, 9, w38);
  for (rr=w38+0, ss=(&w24); rr!=w38+1; rr+=1) *rr = *ss++;
  /* #140: @24 = @19[5] */
  for (rr=(&w24), ss=w19+5; ss!=w19+6; ss+=1) *rr++ = *ss;
  /* #141: (@38[4] = @24) */
  for (rr=w38+4, ss=(&w24); rr!=w38+5; rr+=1) *rr = *ss++;
  /* #142: @24 = @19[6] */
  for (rr=(&w24), ss=w19+6; ss!=w19+7; ss+=1) *rr++ = *ss;
  /* #143: (@38[8] = @24) */
  for (rr=w38+8, ss=(&w24); rr!=w38+9; rr+=1) *rr = *ss++;
  /* #144: @39 = mac(@36,@38,@3) */
  casadi_copy(w3, 3, w39);
  for (i=0, rr=w39; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w36+j, tt=w38+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #145: @24 = mac(@39,@34,@0) */
  casadi_copy((&w0), 1, (&w24));
  for (i=0, rr=(&w24); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w39+j, tt=w34+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #146: @7 = (@7+@24) */
  w7 += w24;
  /* #147: @39 = @32[8:11] */
  for (rr=w39, ss=w32+8; ss!=w32+11; ss+=1) *rr++ = *ss;
  /* #148: @34 = @5[8:11] */
  for (rr=w34, ss=w5+8; ss!=w5+11; ss+=1) *rr++ = *ss;
  /* #149: @39 = (@39-@34) */
  for (i=0, rr=w39, cs=w34; i<3; ++i) (*rr++) -= (*cs++);
  /* #150: @34 = @39' */
  casadi_copy(w39, 3, w34);
  /* #151: @24 = @19[11] */
  for (rr=(&w24), ss=w19+11; ss!=w19+12; ss+=1) *rr++ = *ss;
  /* #152: (@37[0] = @24) */
  for (rr=w37+0, ss=(&w24); rr!=w37+1; rr+=1) *rr = *ss++;
  /* #153: @24 = @19[12] */
  for (rr=(&w24), ss=w19+12; ss!=w19+13; ss+=1) *rr++ = *ss;
  /* #154: (@37[4] = @24) */
  for (rr=w37+4, ss=(&w24); rr!=w37+5; rr+=1) *rr = *ss++;
  /* #155: @24 = @19[13] */
  for (rr=(&w24), ss=w19+13; ss!=w19+14; ss+=1) *rr++ = *ss;
  /* #156: (@37[8] = @24) */
  for (rr=w37+8, ss=(&w24); rr!=w37+9; rr+=1) *rr = *ss++;
  /* #157: @3 = mac(@34,@37,@3) */
  for (i=0, rr=w3; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w34+j, tt=w37+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #158: @0 = mac(@3,@39,@0) */
  for (i=0, rr=(&w0); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w3+j, tt=w39+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #159: @7 = (@7+@0) */
  w7 += w0;
  /* #160: output[0][0] = @7 */
  if (res[0]) res[0][0] = w7;
  return 0;
}

CASADI_SYMBOL_EXPORT int dq_quadrotor_cost_ext_cost_e_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int dq_quadrotor_cost_ext_cost_e_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int dq_quadrotor_cost_ext_cost_e_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void dq_quadrotor_cost_ext_cost_e_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int dq_quadrotor_cost_ext_cost_e_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void dq_quadrotor_cost_ext_cost_e_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void dq_quadrotor_cost_ext_cost_e_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void dq_quadrotor_cost_ext_cost_e_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int dq_quadrotor_cost_ext_cost_e_fun_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int dq_quadrotor_cost_ext_cost_e_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real dq_quadrotor_cost_ext_cost_e_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* dq_quadrotor_cost_ext_cost_e_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* dq_quadrotor_cost_ext_cost_e_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* dq_quadrotor_cost_ext_cost_e_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* dq_quadrotor_cost_ext_cost_e_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int dq_quadrotor_cost_ext_cost_e_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 18;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 402;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
