/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) dq_quadrotor_cost_ext_cost_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_norm_2 CASADI_PREFIX(norm_2)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_zeros CASADI_PREFIX(zeros)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

casadi_real casadi_norm_2(casadi_int n, const casadi_real* x) {
  return sqrt(casadi_dot(n, x, x));
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

static const casadi_int casadi_s0[3] = {14, 1, 1};
static const casadi_int casadi_s1[3] = {4, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};
static const casadi_int casadi_s3[3] = {50, 1, 1};
static const casadi_int casadi_s4[3] = {1, 1, 1};

static const casadi_real casadi_zeros[32] = 
  {0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.};

/* dq_quadrotor_cost_ext_cost_fun:(i0[14],i1[4],i2[0],i3[50])->(o0) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, w00, *w01=w+9, w02, *w03=w+18, *w04=w+21, w06, w07, w08, w09, *w10=w+51, w11;
  casadi_real w12, *w13=w+57, *w14=w+61, *w15=w+65, *w16=w+69, *w17=w+85, *w18=w+101, *w19=w+133, *w20=w+165, *w21=w+181, *w22=w+197, *w23=w+229;
  casadi_real *w24=w+293, w25, w26, w27, w28, w29, w30, w31, w32, *w33=w+365, *w34=w+379, *w35=w+387;
  casadi_real *w36=w+390, *w37=w+394, *w38=w+397, *w39=w+406, *w40=w+415;
  const casadi_real *cr, *cs, *ct, *wr05, *wr13, *wr15, *wr19, *wr35, *wr37;
  /* #0: @0 = 0 */
  w00 = 0.;
  /* #1: @1 = zeros(1x8) */
  casadi_clear(w01, 8);
  /* #2: @2 = 0.5 */
  w02 = 5.0000000000000000e-01;
  /* #3: @3 = all_2.22045e-16(3x1) */
  casadi_fill(w03, 3, 2.2204460492503131e-16);
  /* #4: @4 = zeros(8x1) */
  casadi_clear(w04, 8);
  /* #5: @5 = input[3][0] */
  wr05 = arg[3] ? arg[3] : casadi_zeros;
  /* #6: @6 = @5[0] */
  w06 = wr05[0];
  /* #7: @7 = @5[1] */
  w07 = wr05[1];
  /* #8: @8 = @5[2] */
  w08 = wr05[2];
  /* #9: @9 = @5[3] */
  w09 = wr05[3];
  /* #10: @10 = horzcat(@6, @7, @8, @9) */
  rr=w10;
  *rr++ = w06;
  *rr++ = w07;
  *rr++ = w08;
  *rr++ = w09;
  /* #11: @10 = @10' */
  /* #12: @11 = (-@7) */
  w11 = (- w07 );
  /* #13: @12 = (-@8) */
  w12 = (- w08 );
  /* #14: @13 = horzcat(@11, @6, @9, @12) */
  rr=w13;
  *rr++ = w11;
  *rr++ = w06;
  *rr++ = w09;
  *rr++ = w12;
  /* #15: @13 = @13' */
  /* #16: @9 = (-@9) */
  w09 = (- w09 );
  /* #17: @14 = horzcat(@12, @9, @6, @7) */
  rr=w14;
  *rr++ = w12;
  *rr++ = w09;
  *rr++ = w06;
  *rr++ = w07;
  /* #18: @14 = @14' */
  /* #19: @15 = horzcat(@9, @8, @11, @6) */
  rr=w15;
  *rr++ = w09;
  *rr++ = w08;
  *rr++ = w11;
  *rr++ = w06;
  /* #20: @15 = @15' */
  /* #21: @16 = horzcat(@10, @13, @14, @15) */
  rr=w16;
  for (i=0, cs=w10; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w13; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w14; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w15; i<4; ++i) *rr++ = *cs++;
  /* #22: @17 = @16' */
  for (i=0, rr=w17, cs=w16; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #23: @16 = zeros(4x4) */
  casadi_clear(w16, 16);
  /* #24: @18 = horzcat(@17, @16) */
  rr=w18;
  for (i=0, cs=w17; i<16; ++i) *rr++ = *cs++;
  for (i=0, cs=w16; i<16; ++i) *rr++ = *cs++;
  /* #25: @19 = @18' */
  for (i=0, rr=w19, cs=w18; i<8; ++i) for (j=0; j<4; ++j) rr[i+j*8] = *cs++;
  /* #26: @9 = @5[4] */
  w09 = wr05[4];
  /* #27: @8 = @5[5] */
  w08 = wr05[5];
  /* #28: @11 = @5[6] */
  w11 = wr05[6];
  /* #29: @6 = @5[7] */
  w06 = wr05[7];
  /* #30: @10 = horzcat(@9, @8, @11, @6) */
  rr=w10;
  *rr++ = w09;
  *rr++ = w08;
  *rr++ = w11;
  *rr++ = w06;
  /* #31: @10 = @10' */
  /* #32: @12 = (-@8) */
  w12 = (- w08 );
  /* #33: @7 = (-@11) */
  w07 = (- w11 );
  /* #34: @13 = horzcat(@12, @9, @6, @7) */
  rr=w13;
  *rr++ = w12;
  *rr++ = w09;
  *rr++ = w06;
  *rr++ = w07;
  /* #35: @13 = @13' */
  /* #36: @6 = (-@6) */
  w06 = (- w06 );
  /* #37: @14 = horzcat(@7, @6, @9, @8) */
  rr=w14;
  *rr++ = w07;
  *rr++ = w06;
  *rr++ = w09;
  *rr++ = w08;
  /* #38: @14 = @14' */
  /* #39: @15 = horzcat(@6, @11, @12, @9) */
  rr=w15;
  *rr++ = w06;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w09;
  /* #40: @15 = @15' */
  /* #41: @20 = horzcat(@10, @13, @14, @15) */
  rr=w20;
  for (i=0, cs=w10; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w13; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w14; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w15; i<4; ++i) *rr++ = *cs++;
  /* #42: @21 = @20' */
  for (i=0, rr=w21, cs=w20; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #43: @18 = horzcat(@21, @17) */
  rr=w18;
  for (i=0, cs=w21; i<16; ++i) *rr++ = *cs++;
  for (i=0, cs=w17; i<16; ++i) *rr++ = *cs++;
  /* #44: @22 = @18' */
  for (i=0, rr=w22, cs=w18; i<8; ++i) for (j=0; j<4; ++j) rr[i+j*8] = *cs++;
  /* #45: @23 = horzcat(@19, @22) */
  rr=w23;
  for (i=0, cs=w19; i<32; ++i) *rr++ = *cs++;
  for (i=0, cs=w22; i<32; ++i) *rr++ = *cs++;
  /* #46: @24 = @23' */
  for (i=0, rr=w24, cs=w23; i<8; ++i) for (j=0; j<8; ++j) rr[i+j*8] = *cs++;
  /* #47: @6 = input[0][0] */
  w06 = arg[0] ? arg[0][0] : 0;
  /* #48: @11 = input[0][1] */
  w11 = arg[0] ? arg[0][1] : 0;
  /* #49: @12 = input[0][2] */
  w12 = arg[0] ? arg[0][2] : 0;
  /* #50: @9 = input[0][3] */
  w09 = arg[0] ? arg[0][3] : 0;
  /* #51: @7 = input[0][4] */
  w07 = arg[0] ? arg[0][4] : 0;
  /* #52: @8 = input[0][5] */
  w08 = arg[0] ? arg[0][5] : 0;
  /* #53: @25 = input[0][6] */
  w25 = arg[0] ? arg[0][6] : 0;
  /* #54: @26 = input[0][7] */
  w26 = arg[0] ? arg[0][7] : 0;
  /* #55: @27 = input[0][8] */
  w27 = arg[0] ? arg[0][8] : 0;
  /* #56: @28 = input[0][9] */
  w28 = arg[0] ? arg[0][9] : 0;
  /* #57: @29 = input[0][10] */
  w29 = arg[0] ? arg[0][10] : 0;
  /* #58: @30 = input[0][11] */
  w30 = arg[0] ? arg[0][11] : 0;
  /* #59: @31 = input[0][12] */
  w31 = arg[0] ? arg[0][12] : 0;
  /* #60: @32 = input[0][13] */
  w32 = arg[0] ? arg[0][13] : 0;
  /* #61: @33 = vertcat(@6, @11, @12, @9, @7, @8, @25, @26, @27, @28, @29, @30, @31, @32) */
  rr=w33;
  *rr++ = w06;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w09;
  *rr++ = w07;
  *rr++ = w08;
  *rr++ = w25;
  *rr++ = w26;
  *rr++ = w27;
  *rr++ = w28;
  *rr++ = w29;
  *rr++ = w30;
  *rr++ = w31;
  *rr++ = w32;
  /* #62: @34 = @33[:8] */
  for (rr=w34, cs=w33+0; cs!=w33+8; cs+=1) *rr++ = *cs;
  /* #63: @4 = mac(@24,@34,@4) */
  for (i=0, rr=w04; i<1; ++i) for (j=0; j<8; ++j, ++rr) for (k=0, cs=w24+j, ct=w34+i*8; k<8; ++k) *rr += cs[k*8]**ct++;
  /* #64: @35 = @4[1:4] */
  for (rr=w35, cs=w04+1; cs!=w04+4; cs+=1) *rr++ = *cs;
  /* #65: @3 = (@3+@35) */
  for (i=0, rr=w03, cs=w35; i<3; ++i) (*rr++) += (*cs++);
  /* #66: @6 = ||@3||_F */
  w06 = casadi_norm_2(3, w03);
  /* #67: @11 = @4[0] */
  for (rr=(&w11), cs=w04+0; cs!=w04+1; cs+=1) *rr++ = *cs;
  /* #68: @12 = atan2(@6,@11) */
  w12  = atan2(w06,w11);
  /* #69: @12 = (2.*@12) */
  w12 = (2.* w12 );
  /* #70: @12 = (@2*@12) */
  w12  = (w02*w12);
  /* #71: @9 = @4[1] */
  for (rr=(&w09), cs=w04+1; cs!=w04+2; cs+=1) *rr++ = *cs;
  /* #72: @7 = (@12*@9) */
  w07  = (w12*w09);
  /* #73: @7 = (@7/@6) */
  w07 /= w06;
  /* #74: @8 = @4[2] */
  for (rr=(&w08), cs=w04+2; cs!=w04+3; cs+=1) *rr++ = *cs;
  /* #75: @25 = (@12*@8) */
  w25  = (w12*w08);
  /* #76: @25 = (@25/@6) */
  w25 /= w06;
  /* #77: @26 = @4[3] */
  for (rr=(&w26), cs=w04+3; cs!=w04+4; cs+=1) *rr++ = *cs;
  /* #78: @12 = (@12*@26) */
  w12 *= w26;
  /* #79: @12 = (@12/@6) */
  w12 /= w06;
  /* #80: @10 = zeros(4x1) */
  casadi_clear(w10, 4);
  /* #81: @6 = @4[4] */
  for (rr=(&w06), cs=w04+4; cs!=w04+5; cs+=1) *rr++ = *cs;
  /* #82: @27 = @4[5] */
  for (rr=(&w27), cs=w04+5; cs!=w04+6; cs+=1) *rr++ = *cs;
  /* #83: @28 = (-@27) */
  w28 = (- w27 );
  /* #84: @29 = @4[6] */
  for (rr=(&w29), cs=w04+6; cs!=w04+7; cs+=1) *rr++ = *cs;
  /* #85: @30 = (-@29) */
  w30 = (- w29 );
  /* #86: @31 = @4[7] */
  for (rr=(&w31), cs=w04+7; cs!=w04+8; cs+=1) *rr++ = *cs;
  /* #87: @32 = (-@31) */
  w32 = (- w31 );
  /* #88: @13 = horzcat(@6, @28, @30, @32) */
  rr=w13;
  *rr++ = w06;
  *rr++ = w28;
  *rr++ = w30;
  *rr++ = w32;
  /* #89: @13 = @13' */
  /* #90: @14 = horzcat(@27, @6, @32, @29) */
  rr=w14;
  *rr++ = w27;
  *rr++ = w06;
  *rr++ = w32;
  *rr++ = w29;
  /* #91: @14 = @14' */
  /* #92: @15 = horzcat(@29, @31, @6, @28) */
  rr=w15;
  *rr++ = w29;
  *rr++ = w31;
  *rr++ = w06;
  *rr++ = w28;
  /* #93: @15 = @15' */
  /* #94: @36 = horzcat(@31, @30, @27, @6) */
  rr=w36;
  *rr++ = w31;
  *rr++ = w30;
  *rr++ = w27;
  *rr++ = w06;
  /* #95: @36 = @36' */
  /* #96: @21 = horzcat(@13, @14, @15, @36) */
  rr=w21;
  for (i=0, cs=w13; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w14; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w15; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w36; i<4; ++i) *rr++ = *cs++;
  /* #97: @17 = @21' */
  for (i=0, rr=w17, cs=w21; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #98: @17 = (2.*@17) */
  for (i=0, rr=w17, cs=w17; i<16; ++i) *rr++ = (2.* *cs++ );
  /* #99: @9 = (-@9) */
  w09 = (- w09 );
  /* #100: @8 = (-@8) */
  w08 = (- w08 );
  /* #101: @26 = (-@26) */
  w26 = (- w26 );
  /* #102: @13 = vertcat(@11, @9, @8, @26) */
  rr=w13;
  *rr++ = w11;
  *rr++ = w09;
  *rr++ = w08;
  *rr++ = w26;
  /* #103: @10 = mac(@17,@13,@10) */
  for (i=0, rr=w10; i<1; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, cs=w17+j, ct=w13+i*4; k<4; ++k) *rr += cs[k*4]**ct++;
  /* #104: @11 = @10[1] */
  for (rr=(&w11), cs=w10+1; cs!=w10+2; cs+=1) *rr++ = *cs;
  /* #105: @11 = (@2*@11) */
  w11  = (w02*w11);
  /* #106: @9 = @10[2] */
  for (rr=(&w09), cs=w10+2; cs!=w10+3; cs+=1) *rr++ = *cs;
  /* #107: @9 = (@2*@9) */
  w09  = (w02*w09);
  /* #108: @8 = @10[3] */
  for (rr=(&w08), cs=w10+3; cs!=w10+4; cs+=1) *rr++ = *cs;
  /* #109: @2 = (@2*@8) */
  w02 *= w08;
  /* #110: @4 = vertcat(@0, @7, @25, @12, @0, @11, @9, @2) */
  rr=w04;
  *rr++ = w00;
  *rr++ = w07;
  *rr++ = w25;
  *rr++ = w12;
  *rr++ = w00;
  *rr++ = w11;
  *rr++ = w09;
  *rr++ = w02;
  /* #111: @34 = @4' */
  casadi_copy(w04, 8, w34);
  /* #112: @24 = zeros(8x8) */
  casadi_clear(w24, 64);
  /* #113: @19 = input[3][1] */
  wr19 = arg[3] ? arg[3]+18 : casadi_zeros;
  /* #114: @7 = @19[7] */
  w07 = wr19[7];
  /* #115: (@24[0] = @7) */
  for (rr=w24+0, cs=(&w07); rr!=w24+1; rr+=1) *rr = *cs++;
  /* #116: @7 = @19[8] */
  w07 = wr19[8];
  /* #117: (@24[9] = @7) */
  for (rr=w24+9, cs=(&w07); rr!=w24+10; rr+=1) *rr = *cs++;
  /* #118: @7 = @19[9] */
  w07 = wr19[9];
  /* #119: (@24[18] = @7) */
  for (rr=w24+18, cs=(&w07); rr!=w24+19; rr+=1) *rr = *cs++;
  /* #120: @7 = @19[10] */
  w07 = wr19[10];
  /* #121: (@24[27] = @7) */
  for (rr=w24+27, cs=(&w07); rr!=w24+28; rr+=1) *rr = *cs++;
  /* #122: @7 = @19[0] */
  w07 = wr19[0];
  /* #123: (@24[36] = @7) */
  for (rr=w24+36, cs=(&w07); rr!=w24+37; rr+=1) *rr = *cs++;
  /* #124: @7 = @19[1] */
  w07 = wr19[1];
  /* #125: (@24[45] = @7) */
  for (rr=w24+45, cs=(&w07); rr!=w24+46; rr+=1) *rr = *cs++;
  /* #126: @7 = @19[2] */
  w07 = wr19[2];
  /* #127: (@24[54] = @7) */
  for (rr=w24+54, cs=(&w07); rr!=w24+55; rr+=1) *rr = *cs++;
  /* #128: @7 = @19[3] */
  w07 = wr19[3];
  /* #129: (@24[63] = @7) */
  for (rr=w24+63, cs=(&w07); rr!=w24+64; rr+=1) *rr = *cs++;
  /* #130: @1 = mac(@34,@24,@1) */
  for (i=0, rr=w01; i<8; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w34+j, ct=w24+i*8; k<8; ++k) *rr += cs[k*1]**ct++;
  /* #131: @7 = mac(@1,@4,@0) */
  casadi_copy((&w00), 1, (&w07));
  for (i=0, rr=(&w07); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w01+j, ct=w04+i*8; k<8; ++k) *rr += cs[k*1]**ct++;
  /* #132: @10 = zeros(1x4) */
  casadi_clear(w10, 4);
  /* #133: @13 = @5[14:18] */
  wr13 = wr05+14;
  /* #134: @25 = input[1][0] */
  w25 = arg[1] ? arg[1][0] : 0;
  /* #135: @12 = input[1][1] */
  w12 = arg[1] ? arg[1][1] : 0;
  /* #136: @11 = input[1][2] */
  w11 = arg[1] ? arg[1][2] : 0;
  /* #137: @9 = input[1][3] */
  w09 = arg[1] ? arg[1][3] : 0;
  /* #138: @14 = vertcat(@25, @12, @11, @9) */
  rr=w14;
  *rr++ = w25;
  *rr++ = w12;
  *rr++ = w11;
  *rr++ = w09;
  /* #139: @13 = (@13-@14) */
  for (i=0, rr=w13, cr=wr13, cs=w14; i<4; ++i) (*rr++)  = ((*cr++)-(*cs++));
  /* #140: @14 = @13' */
  casadi_copy(w13, 4, w14);
  /* #141: @15 = @19[28:32] */
  wr15 = wr19+28;
  /* #142: @25 = @19[28] */
  w25 = wr19[28];
  /* #143: @12 = 82 */
  w12 = 82.;
  /* #144: @25 = (@25/@12) */
  w25 /= w12;
  /* #145: (@15[0] = @25) */
  casadi_copy(wr15, 4, w15);
  for (rr=w15+0, cs=(&w25); rr!=w15+1; rr+=1) *rr = *cs++;
  /* #146: @25 = @15[1] */
  for (rr=(&w25), cs=w15+1; cs!=w15+2; cs+=1) *rr++ = *cs;
  /* #147: @25 = (2.*@25) */
  w25 = (2.* w25 );
  /* #148: (@15[1] = @25) */
  for (rr=w15+1, cs=(&w25); rr!=w15+2; rr+=1) *rr = *cs++;
  /* #149: @25 = @15[2] */
  for (rr=(&w25), cs=w15+2; cs!=w15+3; cs+=1) *rr++ = *cs;
  /* #150: @25 = (2.*@25) */
  w25 = (2.* w25 );
  /* #151: (@15[2] = @25) */
  for (rr=w15+2, cs=(&w25); rr!=w15+3; rr+=1) *rr = *cs++;
  /* #152: @25 = @15[3] */
  for (rr=(&w25), cs=w15+3; cs!=w15+4; cs+=1) *rr++ = *cs;
  /* #153: @25 = (2.*@25) */
  w25 = (2.* w25 );
  /* #154: (@15[3] = @25) */
  for (rr=w15+3, cs=(&w25); rr!=w15+4; rr+=1) *rr = *cs++;
  /* #155: @25 = @15[0] */
  for (rr=(&w25), cs=w15+0; cs!=w15+1; cs+=1) *rr++ = *cs;
  /* #156: (@16[0] = @25) */
  for (rr=w16+0, cs=(&w25); rr!=w16+1; rr+=1) *rr = *cs++;
  /* #157: @25 = @15[1] */
  for (rr=(&w25), cs=w15+1; cs!=w15+2; cs+=1) *rr++ = *cs;
  /* #158: (@16[5] = @25) */
  for (rr=w16+5, cs=(&w25); rr!=w16+6; rr+=1) *rr = *cs++;
  /* #159: @25 = @15[2] */
  for (rr=(&w25), cs=w15+2; cs!=w15+3; cs+=1) *rr++ = *cs;
  /* #160: (@16[10] = @25) */
  for (rr=w16+10, cs=(&w25); rr!=w16+11; rr+=1) *rr = *cs++;
  /* #161: @25 = @15[3] */
  for (rr=(&w25), cs=w15+3; cs!=w15+4; cs+=1) *rr++ = *cs;
  /* #162: (@16[15] = @25) */
  for (rr=w16+15, cs=(&w25); rr!=w16+16; rr+=1) *rr = *cs++;
  /* #163: @10 = mac(@14,@16,@10) */
  for (i=0, rr=w10; i<4; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w14+j, ct=w16+i*4; k<4; ++k) *rr += cs[k*1]**ct++;
  /* #164: @25 = mac(@10,@13,@0) */
  casadi_copy((&w00), 1, (&w25));
  for (i=0, rr=(&w25); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w10+j, ct=w13+i*4; k<4; ++k) *rr += cs[k*1]**ct++;
  /* #165: @7 = (@7+@25) */
  w07 += w25;
  /* #166: @3 = zeros(1x3) */
  casadi_clear(w03, 3);
  /* #167: @35 = @33[11:14] */
  for (rr=w35, cs=w33+11; cs!=w33+14; cs+=1) *rr++ = *cs;
  /* #168: @37 = @5[11:14] */
  wr37 = wr05+11;
  /* #169: @35 = (@35-@37) */
  for (i=0, rr=w35, cs=wr37; i<3; ++i) (*rr++) -= (*cs++);
  /* #170: @37 = @35' */
  casadi_copy(w35, 3, w37);
  /* #171: @38 = zeros(3x3) */
  casadi_clear(w38, 9);
  /* #172: @25 = @19[4] */
  w25 = wr19[4];
  /* #173: @39 = @38; (@39[0] = @25) */
  casadi_copy(w38, 9, w39);
  for (rr=w39+0, cs=(&w25); rr!=w39+1; rr+=1) *rr = *cs++;
  /* #174: @25 = @19[5] */
  w25 = wr19[5];
  /* #175: (@39[4] = @25) */
  for (rr=w39+4, cs=(&w25); rr!=w39+5; rr+=1) *rr = *cs++;
  /* #176: @25 = @19[6] */
  w25 = wr19[6];
  /* #177: (@39[8] = @25) */
  for (rr=w39+8, cs=(&w25); rr!=w39+9; rr+=1) *rr = *cs++;
  /* #178: @40 = mac(@37,@39,@3) */
  casadi_copy(w03, 3, w40);
  for (i=0, rr=w40; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w37+j, ct=w39+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #179: @25 = mac(@40,@35,@0) */
  casadi_copy((&w00), 1, (&w25));
  for (i=0, rr=(&w25); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w40+j, ct=w35+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #180: @7 = (@7+@25) */
  w07 += w25;
  /* #181: @40 = @33[8:11] */
  for (rr=w40, cs=w33+8; cs!=w33+11; cs+=1) *rr++ = *cs;
  /* #182: @35 = @5[8:11] */
  wr35 = wr05+8;
  /* #183: @40 = (@40-@35) */
  for (i=0, rr=w40, cs=wr35; i<3; ++i) (*rr++) -= (*cs++);
  /* #184: @35 = @40' */
  casadi_copy(w40, 3, w35);
  /* #185: @25 = @19[11] */
  w25 = wr19[11];
  /* #186: (@38[0] = @25) */
  for (rr=w38+0, cs=(&w25); rr!=w38+1; rr+=1) *rr = *cs++;
  /* #187: @25 = @19[12] */
  w25 = wr19[12];
  /* #188: (@38[4] = @25) */
  for (rr=w38+4, cs=(&w25); rr!=w38+5; rr+=1) *rr = *cs++;
  /* #189: @25 = @19[13] */
  w25 = wr19[13];
  /* #190: (@38[8] = @25) */
  for (rr=w38+8, cs=(&w25); rr!=w38+9; rr+=1) *rr = *cs++;
  /* #191: @3 = mac(@35,@38,@3) */
  for (i=0, rr=w03; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w35+j, ct=w38+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #192: @0 = mac(@3,@40,@0) */
  for (i=0, rr=(&w00); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w03+j, ct=w40+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #193: @7 = (@7+@0) */
  w07 += w00;
  /* #194: output[0][0] = @7 */
  if (res[0]) res[0][0] = w07;
  return 0;
}

CASADI_SYMBOL_EXPORT int dq_quadrotor_cost_ext_cost_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int dq_quadrotor_cost_ext_cost_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int dq_quadrotor_cost_ext_cost_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void dq_quadrotor_cost_ext_cost_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int dq_quadrotor_cost_ext_cost_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void dq_quadrotor_cost_ext_cost_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void dq_quadrotor_cost_ext_cost_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void dq_quadrotor_cost_ext_cost_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int dq_quadrotor_cost_ext_cost_fun_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int dq_quadrotor_cost_ext_cost_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real dq_quadrotor_cost_ext_cost_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* dq_quadrotor_cost_ext_cost_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* dq_quadrotor_cost_ext_cost_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* dq_quadrotor_cost_ext_cost_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* dq_quadrotor_cost_ext_cost_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int dq_quadrotor_cost_ext_cost_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 18;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 418;
  return 0;
}

CASADI_SYMBOL_EXPORT int dq_quadrotor_cost_ext_cost_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 18*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 418*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
