/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) dq_quadrotor_cost_ext_cost_e_fun_jac_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_norm_2 CASADI_PREFIX(norm_2)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_zeros CASADI_PREFIX(zeros)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

casadi_real casadi_norm_2(casadi_int n, const casadi_real* x) {
  return sqrt(casadi_dot(n, x, x));
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {14, 1, 1};
static const casadi_int casadi_s1[3] = {0, 1, 1};
static const casadi_int casadi_s2[3] = {50, 1, 1};
static const casadi_int casadi_s3[3] = {1, 1, 1};

static const casadi_real casadi_zeros[32] = 
  {0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.};

/* dq_quadrotor_cost_ext_cost_e_fun_jac:(i0[14],i1[0],i2[0],i3[50])->(o0,o1[14]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, w00, *w01=w+9, w02, *w03=w+18, *w04=w+21, w06, w07, w08, w09, *w10=w+51, w11;
  casadi_real w12, *w13=w+57, *w14=w+61, *w15=w+65, *w16=w+69, *w17=w+85, *w18=w+101, *w19=w+133, *w20=w+165, *w21=w+181, *w22=w+197, *w23=w+229;
  casadi_real *w24=w+293, w25, w26, w27, w28, w29, w30, w31, w32, *w33=w+365, *w34=w+379, *w35=w+387;
  casadi_real *w36=w+395, w37, w38, *w39=w+400, *w40=w+404, *w41=w+412, *w42=w+415, *w43=w+418, *w44=w+427, *w45=w+436, *w46=w+439, *w47=w+442;
  casadi_real *w48=w+445, *w49=w+454;
  const casadi_real *cs, *ct, *wr05, *wr19, *wr42, *wr46;
  /* #0: @0 = 0 */
  w00 = 0.;
  /* #1: @1 = zeros(1x8) */
  casadi_clear(w01, 8);
  /* #2: @2 = 0.5 */
  w02 = 5.0000000000000000e-01;
  /* #3: @3 = all_2.22045e-16(3x1) */
  casadi_fill(w03, 3, 2.2204460492503131e-16);
  /* #4: @4 = zeros(8x1) */
  casadi_clear(w04, 8);
  /* #5: @5 = input[3][0] */
  wr05 = arg[3] ? arg[3] : casadi_zeros;
  /* #6: @6 = @5[0] */
  w06 = wr05[0];
  /* #7: @7 = @5[1] */
  w07 = wr05[1];
  /* #8: @8 = @5[2] */
  w08 = wr05[2];
  /* #9: @9 = @5[3] */
  w09 = wr05[3];
  /* #10: @10 = horzcat(@6, @7, @8, @9) */
  rr=w10;
  *rr++ = w06;
  *rr++ = w07;
  *rr++ = w08;
  *rr++ = w09;
  /* #11: @10 = @10' */
  /* #12: @11 = (-@7) */
  w11 = (- w07 );
  /* #13: @12 = (-@8) */
  w12 = (- w08 );
  /* #14: @13 = horzcat(@11, @6, @9, @12) */
  rr=w13;
  *rr++ = w11;
  *rr++ = w06;
  *rr++ = w09;
  *rr++ = w12;
  /* #15: @13 = @13' */
  /* #16: @9 = (-@9) */
  w09 = (- w09 );
  /* #17: @14 = horzcat(@12, @9, @6, @7) */
  rr=w14;
  *rr++ = w12;
  *rr++ = w09;
  *rr++ = w06;
  *rr++ = w07;
  /* #18: @14 = @14' */
  /* #19: @15 = horzcat(@9, @8, @11, @6) */
  rr=w15;
  *rr++ = w09;
  *rr++ = w08;
  *rr++ = w11;
  *rr++ = w06;
  /* #20: @15 = @15' */
  /* #21: @16 = horzcat(@10, @13, @14, @15) */
  rr=w16;
  for (i=0, cs=w10; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w13; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w14; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w15; i<4; ++i) *rr++ = *cs++;
  /* #22: @17 = @16' */
  for (i=0, rr=w17, cs=w16; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #23: @16 = zeros(4x4) */
  casadi_clear(w16, 16);
  /* #24: @18 = horzcat(@17, @16) */
  rr=w18;
  for (i=0, cs=w17; i<16; ++i) *rr++ = *cs++;
  for (i=0, cs=w16; i<16; ++i) *rr++ = *cs++;
  /* #25: @19 = @18' */
  for (i=0, rr=w19, cs=w18; i<8; ++i) for (j=0; j<4; ++j) rr[i+j*8] = *cs++;
  /* #26: @9 = @5[4] */
  w09 = wr05[4];
  /* #27: @8 = @5[5] */
  w08 = wr05[5];
  /* #28: @11 = @5[6] */
  w11 = wr05[6];
  /* #29: @6 = @5[7] */
  w06 = wr05[7];
  /* #30: @10 = horzcat(@9, @8, @11, @6) */
  rr=w10;
  *rr++ = w09;
  *rr++ = w08;
  *rr++ = w11;
  *rr++ = w06;
  /* #31: @10 = @10' */
  /* #32: @12 = (-@8) */
  w12 = (- w08 );
  /* #33: @7 = (-@11) */
  w07 = (- w11 );
  /* #34: @13 = horzcat(@12, @9, @6, @7) */
  rr=w13;
  *rr++ = w12;
  *rr++ = w09;
  *rr++ = w06;
  *rr++ = w07;
  /* #35: @13 = @13' */
  /* #36: @6 = (-@6) */
  w06 = (- w06 );
  /* #37: @14 = horzcat(@7, @6, @9, @8) */
  rr=w14;
  *rr++ = w07;
  *rr++ = w06;
  *rr++ = w09;
  *rr++ = w08;
  /* #38: @14 = @14' */
  /* #39: @15 = horzcat(@6, @11, @12, @9) */
  rr=w15;
  *rr++ = w06;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w09;
  /* #40: @15 = @15' */
  /* #41: @20 = horzcat(@10, @13, @14, @15) */
  rr=w20;
  for (i=0, cs=w10; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w13; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w14; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w15; i<4; ++i) *rr++ = *cs++;
  /* #42: @21 = @20' */
  for (i=0, rr=w21, cs=w20; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #43: @18 = horzcat(@21, @17) */
  rr=w18;
  for (i=0, cs=w21; i<16; ++i) *rr++ = *cs++;
  for (i=0, cs=w17; i<16; ++i) *rr++ = *cs++;
  /* #44: @22 = @18' */
  for (i=0, rr=w22, cs=w18; i<8; ++i) for (j=0; j<4; ++j) rr[i+j*8] = *cs++;
  /* #45: @23 = horzcat(@19, @22) */
  rr=w23;
  for (i=0, cs=w19; i<32; ++i) *rr++ = *cs++;
  for (i=0, cs=w22; i<32; ++i) *rr++ = *cs++;
  /* #46: @24 = @23' */
  for (i=0, rr=w24, cs=w23; i<8; ++i) for (j=0; j<8; ++j) rr[i+j*8] = *cs++;
  /* #47: @6 = input[0][0] */
  w06 = arg[0] ? arg[0][0] : 0;
  /* #48: @11 = input[0][1] */
  w11 = arg[0] ? arg[0][1] : 0;
  /* #49: @12 = input[0][2] */
  w12 = arg[0] ? arg[0][2] : 0;
  /* #50: @9 = input[0][3] */
  w09 = arg[0] ? arg[0][3] : 0;
  /* #51: @7 = input[0][4] */
  w07 = arg[0] ? arg[0][4] : 0;
  /* #52: @8 = input[0][5] */
  w08 = arg[0] ? arg[0][5] : 0;
  /* #53: @25 = input[0][6] */
  w25 = arg[0] ? arg[0][6] : 0;
  /* #54: @26 = input[0][7] */
  w26 = arg[0] ? arg[0][7] : 0;
  /* #55: @27 = input[0][8] */
  w27 = arg[0] ? arg[0][8] : 0;
  /* #56: @28 = input[0][9] */
  w28 = arg[0] ? arg[0][9] : 0;
  /* #57: @29 = input[0][10] */
  w29 = arg[0] ? arg[0][10] : 0;
  /* #58: @30 = input[0][11] */
  w30 = arg[0] ? arg[0][11] : 0;
  /* #59: @31 = input[0][12] */
  w31 = arg[0] ? arg[0][12] : 0;
  /* #60: @32 = input[0][13] */
  w32 = arg[0] ? arg[0][13] : 0;
  /* #61: @33 = vertcat(@6, @11, @12, @9, @7, @8, @25, @26, @27, @28, @29, @30, @31, @32) */
  rr=w33;
  *rr++ = w06;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w09;
  *rr++ = w07;
  *rr++ = w08;
  *rr++ = w25;
  *rr++ = w26;
  *rr++ = w27;
  *rr++ = w28;
  *rr++ = w29;
  *rr++ = w30;
  *rr++ = w31;
  *rr++ = w32;
  /* #62: @34 = @33[:8] */
  for (rr=w34, cs=w33+0; cs!=w33+8; cs+=1) *rr++ = *cs;
  /* #63: @35 = mac(@24,@34,@4) */
  casadi_copy(w04, 8, w35);
  for (i=0, rr=w35; i<1; ++i) for (j=0; j<8; ++j, ++rr) for (k=0, cs=w24+j, ct=w34+i*8; k<8; ++k) *rr += cs[k*8]**ct++;
  /* #64: @36 = @35[1:4] */
  for (rr=w36, cs=w35+1; cs!=w35+4; cs+=1) *rr++ = *cs;
  /* #65: @3 = (@3+@36) */
  for (i=0, rr=w03, cs=w36; i<3; ++i) (*rr++) += (*cs++);
  /* #66: @6 = ||@3||_F */
  w06 = casadi_norm_2(3, w03);
  /* #67: @11 = @35[0] */
  for (rr=(&w11), cs=w35+0; cs!=w35+1; cs+=1) *rr++ = *cs;
  /* #68: @12 = atan2(@6,@11) */
  w12  = atan2(w06,w11);
  /* #69: @12 = (2.*@12) */
  w12 = (2.* w12 );
  /* #70: @12 = (@2*@12) */
  w12  = (w02*w12);
  /* #71: @9 = @35[1] */
  for (rr=(&w09), cs=w35+1; cs!=w35+2; cs+=1) *rr++ = *cs;
  /* #72: @7 = (@12*@9) */
  w07  = (w12*w09);
  /* #73: @7 = (@7/@6) */
  w07 /= w06;
  /* #74: @8 = @35[2] */
  for (rr=(&w08), cs=w35+2; cs!=w35+3; cs+=1) *rr++ = *cs;
  /* #75: @25 = (@12*@8) */
  w25  = (w12*w08);
  /* #76: @25 = (@25/@6) */
  w25 /= w06;
  /* #77: @26 = @35[3] */
  for (rr=(&w26), cs=w35+3; cs!=w35+4; cs+=1) *rr++ = *cs;
  /* #78: @27 = (@12*@26) */
  w27  = (w12*w26);
  /* #79: @27 = (@27/@6) */
  w27 /= w06;
  /* #80: @10 = zeros(4x1) */
  casadi_clear(w10, 4);
  /* #81: @28 = @35[4] */
  for (rr=(&w28), cs=w35+4; cs!=w35+5; cs+=1) *rr++ = *cs;
  /* #82: @29 = @35[5] */
  for (rr=(&w29), cs=w35+5; cs!=w35+6; cs+=1) *rr++ = *cs;
  /* #83: @30 = (-@29) */
  w30 = (- w29 );
  /* #84: @31 = @35[6] */
  for (rr=(&w31), cs=w35+6; cs!=w35+7; cs+=1) *rr++ = *cs;
  /* #85: @32 = (-@31) */
  w32 = (- w31 );
  /* #86: @37 = @35[7] */
  for (rr=(&w37), cs=w35+7; cs!=w35+8; cs+=1) *rr++ = *cs;
  /* #87: @38 = (-@37) */
  w38 = (- w37 );
  /* #88: @13 = horzcat(@28, @30, @32, @38) */
  rr=w13;
  *rr++ = w28;
  *rr++ = w30;
  *rr++ = w32;
  *rr++ = w38;
  /* #89: @13 = @13' */
  /* #90: @14 = horzcat(@29, @28, @38, @31) */
  rr=w14;
  *rr++ = w29;
  *rr++ = w28;
  *rr++ = w38;
  *rr++ = w31;
  /* #91: @14 = @14' */
  /* #92: @15 = horzcat(@31, @37, @28, @30) */
  rr=w15;
  *rr++ = w31;
  *rr++ = w37;
  *rr++ = w28;
  *rr++ = w30;
  /* #93: @15 = @15' */
  /* #94: @39 = horzcat(@37, @32, @29, @28) */
  rr=w39;
  *rr++ = w37;
  *rr++ = w32;
  *rr++ = w29;
  *rr++ = w28;
  /* #95: @39 = @39' */
  /* #96: @21 = horzcat(@13, @14, @15, @39) */
  rr=w21;
  for (i=0, cs=w13; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w14; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w15; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w39; i<4; ++i) *rr++ = *cs++;
  /* #97: @17 = @21' */
  for (i=0, rr=w17, cs=w21; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #98: @17 = (2.*@17) */
  for (i=0, rr=w17, cs=w17; i<16; ++i) *rr++ = (2.* *cs++ );
  /* #99: @37 = (-@9) */
  w37 = (- w09 );
  /* #100: @32 = (-@8) */
  w32 = (- w08 );
  /* #101: @29 = (-@26) */
  w29 = (- w26 );
  /* #102: @13 = vertcat(@11, @37, @32, @29) */
  rr=w13;
  *rr++ = w11;
  *rr++ = w37;
  *rr++ = w32;
  *rr++ = w29;
  /* #103: @14 = mac(@17,@13,@10) */
  casadi_copy(w10, 4, w14);
  for (i=0, rr=w14; i<1; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, cs=w17+j, ct=w13+i*4; k<4; ++k) *rr += cs[k*4]**ct++;
  /* #104: @37 = @14[1] */
  for (rr=(&w37), cs=w14+1; cs!=w14+2; cs+=1) *rr++ = *cs;
  /* #105: @37 = (@2*@37) */
  w37  = (w02*w37);
  /* #106: @32 = @14[2] */
  for (rr=(&w32), cs=w14+2; cs!=w14+3; cs+=1) *rr++ = *cs;
  /* #107: @32 = (@2*@32) */
  w32  = (w02*w32);
  /* #108: @29 = @14[3] */
  for (rr=(&w29), cs=w14+3; cs!=w14+4; cs+=1) *rr++ = *cs;
  /* #109: @29 = (@2*@29) */
  w29  = (w02*w29);
  /* #110: @35 = vertcat(@0, @7, @25, @27, @0, @37, @32, @29) */
  rr=w35;
  *rr++ = w00;
  *rr++ = w07;
  *rr++ = w25;
  *rr++ = w27;
  *rr++ = w00;
  *rr++ = w37;
  *rr++ = w32;
  *rr++ = w29;
  /* #111: @34 = @35' */
  casadi_copy(w35, 8, w34);
  /* #112: @24 = zeros(8x8) */
  casadi_clear(w24, 64);
  /* #113: @19 = input[3][1] */
  wr19 = arg[3] ? arg[3]+18 : casadi_zeros;
  /* #114: @37 = @19[7] */
  w37 = wr19[7];
  /* #115: (@24[0] = @37) */
  for (rr=w24+0, cs=(&w37); rr!=w24+1; rr+=1) *rr = *cs++;
  /* #116: @37 = @19[8] */
  w37 = wr19[8];
  /* #117: (@24[9] = @37) */
  for (rr=w24+9, cs=(&w37); rr!=w24+10; rr+=1) *rr = *cs++;
  /* #118: @37 = @19[9] */
  w37 = wr19[9];
  /* #119: (@24[18] = @37) */
  for (rr=w24+18, cs=(&w37); rr!=w24+19; rr+=1) *rr = *cs++;
  /* #120: @37 = @19[10] */
  w37 = wr19[10];
  /* #121: (@24[27] = @37) */
  for (rr=w24+27, cs=(&w37); rr!=w24+28; rr+=1) *rr = *cs++;
  /* #122: @37 = @19[0] */
  w37 = wr19[0];
  /* #123: (@24[36] = @37) */
  for (rr=w24+36, cs=(&w37); rr!=w24+37; rr+=1) *rr = *cs++;
  /* #124: @37 = @19[1] */
  w37 = wr19[1];
  /* #125: (@24[45] = @37) */
  for (rr=w24+45, cs=(&w37); rr!=w24+46; rr+=1) *rr = *cs++;
  /* #126: @37 = @19[2] */
  w37 = wr19[2];
  /* #127: (@24[54] = @37) */
  for (rr=w24+54, cs=(&w37); rr!=w24+55; rr+=1) *rr = *cs++;
  /* #128: @37 = @19[3] */
  w37 = wr19[3];
  /* #129: (@24[63] = @37) */
  for (rr=w24+63, cs=(&w37); rr!=w24+64; rr+=1) *rr = *cs++;
  /* #130: @40 = mac(@34,@24,@1) */
  casadi_copy(w01, 8, w40);
  for (i=0, rr=w40; i<8; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w34+j, ct=w24+i*8; k<8; ++k) *rr += cs[k*1]**ct++;
  /* #131: @37 = mac(@40,@35,@0) */
  casadi_copy((&w00), 1, (&w37));
  for (i=0, rr=(&w37); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w40+j, ct=w35+i*8; k<8; ++k) *rr += cs[k*1]**ct++;
  /* #132: @36 = zeros(1x3) */
  casadi_clear(w36, 3);
  /* #133: @41 = @33[11:14] */
  for (rr=w41, cs=w33+11; cs!=w33+14; cs+=1) *rr++ = *cs;
  /* #134: @42 = @5[11:14] */
  wr42 = wr05+11;
  /* #135: @41 = (@41-@42) */
  for (i=0, rr=w41, cs=wr42; i<3; ++i) (*rr++) -= (*cs++);
  /* #136: @42 = @41' */
  casadi_copy(w41, 3, w42);
  /* #137: @43 = zeros(3x3) */
  casadi_clear(w43, 9);
  /* #138: @32 = @19[4] */
  w32 = wr19[4];
  /* #139: @44 = @43; (@44[0] = @32) */
  casadi_copy(w43, 9, w44);
  for (rr=w44+0, cs=(&w32); rr!=w44+1; rr+=1) *rr = *cs++;
  /* #140: @32 = @19[5] */
  w32 = wr19[5];
  /* #141: (@44[4] = @32) */
  for (rr=w44+4, cs=(&w32); rr!=w44+5; rr+=1) *rr = *cs++;
  /* #142: @32 = @19[6] */
  w32 = wr19[6];
  /* #143: (@44[8] = @32) */
  for (rr=w44+8, cs=(&w32); rr!=w44+9; rr+=1) *rr = *cs++;
  /* #144: @45 = mac(@42,@44,@36) */
  casadi_copy(w36, 3, w45);
  for (i=0, rr=w45; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w42+j, ct=w44+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #145: @32 = mac(@45,@41,@0) */
  casadi_copy((&w00), 1, (&w32));
  for (i=0, rr=(&w32); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w45+j, ct=w41+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #146: @37 = (@37+@32) */
  w37 += w32;
  /* #147: @41 = @33[8:11] */
  for (rr=w41, cs=w33+8; cs!=w33+11; cs+=1) *rr++ = *cs;
  /* #148: @46 = @5[8:11] */
  wr46 = wr05+8;
  /* #149: @41 = (@41-@46) */
  for (i=0, rr=w41, cs=wr46; i<3; ++i) (*rr++) -= (*cs++);
  /* #150: @46 = @41' */
  casadi_copy(w41, 3, w46);
  /* #151: @32 = @19[11] */
  w32 = wr19[11];
  /* #152: (@43[0] = @32) */
  for (rr=w43+0, cs=(&w32); rr!=w43+1; rr+=1) *rr = *cs++;
  /* #153: @32 = @19[12] */
  w32 = wr19[12];
  /* #154: (@43[4] = @32) */
  for (rr=w43+4, cs=(&w32); rr!=w43+5; rr+=1) *rr = *cs++;
  /* #155: @32 = @19[13] */
  w32 = wr19[13];
  /* #156: (@43[8] = @32) */
  for (rr=w43+8, cs=(&w32); rr!=w43+9; rr+=1) *rr = *cs++;
  /* #157: @47 = mac(@46,@43,@36) */
  casadi_copy(w36, 3, w47);
  for (i=0, rr=w47; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w46+j, ct=w43+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #158: @0 = mac(@47,@41,@0) */
  for (i=0, rr=(&w00); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w47+j, ct=w41+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #159: @37 = (@37+@0) */
  w37 += w00;
  /* #160: output[0][0] = @37 */
  if (res[0]) res[0][0] = w37;
  /* #161: @33 = zeros(14x1) */
  casadi_clear(w33, 14);
  /* #162: @47 = @47' */
  /* #163: @48 = @43' */
  for (i=0, rr=w48, cs=w43; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #164: @41 = mac(@46,@48,@36) */
  casadi_copy(w36, 3, w41);
  for (i=0, rr=w41; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w46+j, ct=w48+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #165: @41 = @41' */
  /* #166: @47 = (@47+@41) */
  for (i=0, rr=w47, cs=w41; i<3; ++i) (*rr++) += (*cs++);
  /* #167: (@33[8:11] += @47) */
  for (rr=w33+8, cs=w47; rr!=w33+11; rr+=1) *rr += *cs++;
  /* #168: @45 = @45' */
  /* #169: @48 = @44' */
  for (i=0, rr=w48, cs=w44; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #170: @36 = mac(@42,@48,@36) */
  for (i=0, rr=w36; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w42+j, ct=w48+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #171: @36 = @36' */
  /* #172: @45 = (@45+@36) */
  for (i=0, rr=w45, cs=w36; i<3; ++i) (*rr++) += (*cs++);
  /* #173: (@33[11:14] += @45) */
  for (rr=w33+11, cs=w45; rr!=w33+14; rr+=1) *rr += *cs++;
  /* #174: @21 = @17' */
  for (i=0, rr=w21, cs=w17; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #175: @40 = @40' */
  /* #176: @49 = @24' */
  for (i=0, rr=w49, cs=w24; i<8; ++i) for (j=0; j<8; ++j) rr[i+j*8] = *cs++;
  /* #177: @1 = mac(@34,@49,@1) */
  for (i=0, rr=w01; i<8; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w34+j, ct=w49+i*8; k<8; ++k) *rr += cs[k*1]**ct++;
  /* #178: @1 = @1' */
  /* #179: @40 = (@40+@1) */
  for (i=0, rr=w40, cs=w01; i<8; ++i) (*rr++) += (*cs++);
  /* #180: {NULL, @37, @0, @32, NULL, @29, @28, @31} = vertsplit(@40) */
  w37 = w40[1];
  w00 = w40[2];
  w32 = w40[3];
  w29 = w40[5];
  w28 = w40[6];
  w31 = w40[7];
  /* #181: @31 = (@2*@31) */
  w31  = (w02*w31);
  /* #182: @14 = @10; (@14[3] += @31) */
  casadi_copy(w10, 4, w14);
  for (rr=w14+3, cs=(&w31); rr!=w14+4; rr+=1) *rr += *cs++;
  /* #183: @28 = (@2*@28) */
  w28  = (w02*w28);
  /* #184: (@14[2] += @28) */
  for (rr=w14+2, cs=(&w28); rr!=w14+3; rr+=1) *rr += *cs++;
  /* #185: @29 = (@2*@29) */
  w29  = (w02*w29);
  /* #186: (@14[1] += @29) */
  for (rr=w14+1, cs=(&w29); rr!=w14+2; rr+=1) *rr += *cs++;
  /* #187: @10 = mac(@21,@14,@10) */
  for (i=0, rr=w10; i<1; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, cs=w21+j, ct=w14+i*4; k<4; ++k) *rr += cs[k*4]**ct++;
  /* #188: {@29, @28, @31, @30} = vertsplit(@10) */
  w29 = w10[0];
  w28 = w10[1];
  w31 = w10[2];
  w30 = w10[3];
  /* #189: @30 = (-@30) */
  w30 = (- w30 );
  /* #190: @40 = @4; (@40[3] += @30) */
  casadi_copy(w04, 8, w40);
  for (rr=w40+3, cs=(&w30); rr!=w40+4; rr+=1) *rr += *cs++;
  /* #191: @31 = (-@31) */
  w31 = (- w31 );
  /* #192: (@40[2] += @31) */
  for (rr=w40+2, cs=(&w31); rr!=w40+3; rr+=1) *rr += *cs++;
  /* #193: @28 = (-@28) */
  w28 = (- w28 );
  /* #194: (@40[1] += @28) */
  for (rr=w40+1, cs=(&w28); rr!=w40+2; rr+=1) *rr += *cs++;
  /* #195: (@40[0] += @29) */
  for (rr=w40+0, cs=(&w29); rr!=w40+1; rr+=1) *rr += *cs++;
  /* #196: @13 = @13' */
  /* #197: @16 = mac(@14,@13,@16) */
  for (i=0, rr=w16; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, cs=w14+j, ct=w13+i*1; k<1; ++k) *rr += cs[k*4]**ct++;
  /* #198: @16 = (2.*@16) */
  for (i=0, rr=w16, cs=w16; i<16; ++i) *rr++ = (2.* *cs++ );
  /* #199: @21 = @16' */
  for (i=0, rr=w21, cs=w16; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #200: {@14, @13, @10, @15} = horzsplit(@21) */
  casadi_copy(w21, 4, w14);
  casadi_copy(w21+4, 4, w13);
  casadi_copy(w21+8, 4, w10);
  casadi_copy(w21+12, 4, w15);
  /* #201: @15 = @15' */
  /* #202: {@29, @28, @31, @30} = horzsplit(@15) */
  w29 = w15[0];
  w28 = w15[1];
  w31 = w15[2];
  w30 = w15[3];
  /* #203: (@40[4] += @30) */
  for (rr=w40+4, cs=(&w30); rr!=w40+5; rr+=1) *rr += *cs++;
  /* #204: (@40[5] += @31) */
  for (rr=w40+5, cs=(&w31); rr!=w40+6; rr+=1) *rr += *cs++;
  /* #205: @28 = (-@28) */
  w28 = (- w28 );
  /* #206: (@40[6] += @28) */
  for (rr=w40+6, cs=(&w28); rr!=w40+7; rr+=1) *rr += *cs++;
  /* #207: (@40[7] += @29) */
  for (rr=w40+7, cs=(&w29); rr!=w40+8; rr+=1) *rr += *cs++;
  /* #208: @10 = @10' */
  /* #209: {@29, @28, @31, @30} = horzsplit(@10) */
  w29 = w10[0];
  w28 = w10[1];
  w31 = w10[2];
  w30 = w10[3];
  /* #210: @30 = (-@30) */
  w30 = (- w30 );
  /* #211: (@40[5] += @30) */
  for (rr=w40+5, cs=(&w30); rr!=w40+6; rr+=1) *rr += *cs++;
  /* #212: (@40[4] += @31) */
  for (rr=w40+4, cs=(&w31); rr!=w40+5; rr+=1) *rr += *cs++;
  /* #213: (@40[7] += @28) */
  for (rr=w40+7, cs=(&w28); rr!=w40+8; rr+=1) *rr += *cs++;
  /* #214: (@40[6] += @29) */
  for (rr=w40+6, cs=(&w29); rr!=w40+7; rr+=1) *rr += *cs++;
  /* #215: @13 = @13' */
  /* #216: {@29, @28, @31, @30} = horzsplit(@13) */
  w29 = w13[0];
  w28 = w13[1];
  w31 = w13[2];
  w30 = w13[3];
  /* #217: (@40[6] += @30) */
  for (rr=w40+6, cs=(&w30); rr!=w40+7; rr+=1) *rr += *cs++;
  /* #218: @31 = (-@31) */
  w31 = (- w31 );
  /* #219: (@40[7] += @31) */
  for (rr=w40+7, cs=(&w31); rr!=w40+8; rr+=1) *rr += *cs++;
  /* #220: (@40[4] += @28) */
  for (rr=w40+4, cs=(&w28); rr!=w40+5; rr+=1) *rr += *cs++;
  /* #221: (@40[5] += @29) */
  for (rr=w40+5, cs=(&w29); rr!=w40+6; rr+=1) *rr += *cs++;
  /* #222: @14 = @14' */
  /* #223: {@29, @28, @31, @30} = horzsplit(@14) */
  w29 = w14[0];
  w28 = w14[1];
  w31 = w14[2];
  w30 = w14[3];
  /* #224: @30 = (-@30) */
  w30 = (- w30 );
  /* #225: (@40[7] += @30) */
  for (rr=w40+7, cs=(&w30); rr!=w40+8; rr+=1) *rr += *cs++;
  /* #226: @31 = (-@31) */
  w31 = (- w31 );
  /* #227: (@40[6] += @31) */
  for (rr=w40+6, cs=(&w31); rr!=w40+7; rr+=1) *rr += *cs++;
  /* #228: @28 = (-@28) */
  w28 = (- w28 );
  /* #229: (@40[5] += @28) */
  for (rr=w40+5, cs=(&w28); rr!=w40+6; rr+=1) *rr += *cs++;
  /* #230: (@40[4] += @29) */
  for (rr=w40+4, cs=(&w29); rr!=w40+5; rr+=1) *rr += *cs++;
  /* #231: @29 = (@32/@6) */
  w29  = (w32/w06);
  /* #232: @28 = (@12*@29) */
  w28  = (w12*w29);
  /* #233: (@40[3] += @28) */
  for (rr=w40+3, cs=(&w28); rr!=w40+4; rr+=1) *rr += *cs++;
  /* #234: @28 = (@0/@6) */
  w28  = (w00/w06);
  /* #235: @31 = (@12*@28) */
  w31  = (w12*w28);
  /* #236: (@40[2] += @31) */
  for (rr=w40+2, cs=(&w31); rr!=w40+3; rr+=1) *rr += *cs++;
  /* #237: @31 = (@37/@6) */
  w31  = (w37/w06);
  /* #238: @12 = (@12*@31) */
  w12 *= w31;
  /* #239: (@40[1] += @12) */
  for (rr=w40+1, cs=(&w12); rr!=w40+2; rr+=1) *rr += *cs++;
  /* #240: @12 = sq(@6) */
  w12 = casadi_sq( w06 );
  /* #241: @30 = sq(@11) */
  w30 = casadi_sq( w11 );
  /* #242: @12 = (@12+@30) */
  w12 += w30;
  /* #243: @30 = (@6/@12) */
  w30  = (w06/w12);
  /* #244: @26 = (@26*@29) */
  w26 *= w29;
  /* #245: @26 = (@2*@26) */
  w26  = (w02*w26);
  /* #246: @8 = (@8*@28) */
  w08 *= w28;
  /* #247: @8 = (@2*@8) */
  w08  = (w02*w08);
  /* #248: @26 = (@26+@8) */
  w26 += w08;
  /* #249: @9 = (@9*@31) */
  w09 *= w31;
  /* #250: @2 = (@2*@9) */
  w02 *= w09;
  /* #251: @26 = (@26+@2) */
  w26 += w02;
  /* #252: @26 = (2.*@26) */
  w26 = (2.* w26 );
  /* #253: @30 = (@30*@26) */
  w30 *= w26;
  /* #254: @30 = (-@30) */
  w30 = (- w30 );
  /* #255: (@40[0] += @30) */
  for (rr=w40+0, cs=(&w30); rr!=w40+1; rr+=1) *rr += *cs++;
  /* #256: @25 = (@25/@6) */
  w25 /= w06;
  /* #257: @25 = (@25*@0) */
  w25 *= w00;
  /* #258: @25 = (-@25) */
  w25 = (- w25 );
  /* #259: @27 = (@27/@6) */
  w27 /= w06;
  /* #260: @27 = (@27*@32) */
  w27 *= w32;
  /* #261: @25 = (@25-@27) */
  w25 -= w27;
  /* #262: @7 = (@7/@6) */
  w07 /= w06;
  /* #263: @7 = (@7*@37) */
  w07 *= w37;
  /* #264: @25 = (@25-@7) */
  w25 -= w07;
  /* #265: @11 = (@11/@12) */
  w11 /= w12;
  /* #266: @11 = (@11*@26) */
  w11 *= w26;
  /* #267: @25 = (@25+@11) */
  w25 += w11;
  /* #268: @25 = (@25/@6) */
  w25 /= w06;
  /* #269: @3 = (@25*@3) */
  for (i=0, rr=w03, cs=w03; i<3; ++i) (*rr++)  = (w25*(*cs++));
  /* #270: (@40[1:4] += @3) */
  for (rr=w40+1, cs=w03; rr!=w40+4; rr+=1) *rr += *cs++;
  /* #271: @4 = mac(@23,@40,@4) */
  for (i=0, rr=w04; i<1; ++i) for (j=0; j<8; ++j, ++rr) for (k=0, cs=w23+j, ct=w40+i*8; k<8; ++k) *rr += cs[k*8]**ct++;
  /* #272: (@33[:8] += @4) */
  for (rr=w33+0, cs=w04; rr!=w33+8; rr+=1) *rr += *cs++;
  /* #273: output[1][0] = @33 */
  casadi_copy(w33, 14, res[1]);
  return 0;
}

CASADI_SYMBOL_EXPORT int dq_quadrotor_cost_ext_cost_e_fun_jac(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int dq_quadrotor_cost_ext_cost_e_fun_jac_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int dq_quadrotor_cost_ext_cost_e_fun_jac_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void dq_quadrotor_cost_ext_cost_e_fun_jac_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int dq_quadrotor_cost_ext_cost_e_fun_jac_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void dq_quadrotor_cost_ext_cost_e_fun_jac_release(int mem) {
}

CASADI_SYMBOL_EXPORT void dq_quadrotor_cost_ext_cost_e_fun_jac_incref(void) {
}

CASADI_SYMBOL_EXPORT void dq_quadrotor_cost_ext_cost_e_fun_jac_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int dq_quadrotor_cost_ext_cost_e_fun_jac_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int dq_quadrotor_cost_ext_cost_e_fun_jac_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real dq_quadrotor_cost_ext_cost_e_fun_jac_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* dq_quadrotor_cost_ext_cost_e_fun_jac_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* dq_quadrotor_cost_ext_cost_e_fun_jac_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* dq_quadrotor_cost_ext_cost_e_fun_jac_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* dq_quadrotor_cost_ext_cost_e_fun_jac_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    case 1: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int dq_quadrotor_cost_ext_cost_e_fun_jac_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 18;
  if (sz_res) *sz_res = 10;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 518;
  return 0;
}

CASADI_SYMBOL_EXPORT int dq_quadrotor_cost_ext_cost_e_fun_jac_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 18*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 10*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 518*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
