/* This file was automatically generated by CasADi 3.6.4.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) dq_quadrotor_cost_ext_cost_0_fun_jac_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[18] = {14, 1, 0, 14, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13};
static const casadi_int casadi_s1[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s2[4] = {0, 1, 0, 0};
static const casadi_int casadi_s3[54] = {50, 1, 0, 50, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49};
static const casadi_int casadi_s4[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s5[22] = {18, 1, 0, 18, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17};

/* dq_quadrotor_cost_ext_cost_0_fun_jac:(i0[14],i1[4],i2[0],i3[50])->(o0,o1[18]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *ss, *tt;
  const casadi_real *cs;
  casadi_real w0, *w1=w+9, w2, *w3=w+18, *w4=w+21, *w5=w+29, w6, w7, w8, w9, *w10=w+51, w11, w12, *w13=w+57, *w14=w+61, *w15=w+65, *w16=w+69, *w17=w+85, *w18=w+101, *w19=w+133, *w20=w+165, *w21=w+181, *w22=w+197, *w23=w+229, *w24=w+293, w25, w26, w27, w28, w29, w30, w31, w32, *w33=w+365, *w34=w+379, *w35=w+387, *w36=w+395, w37, w38, *w39=w+400, *w40=w+404, *w41=w+412, *w42=w+416, *w43=w+419, *w44=w+422, *w45=w+431, *w46=w+440, *w47=w+443, *w48=w+446, *w49=w+449, *w50=w+458;
  /* #0: @0 = 0 */
  w0 = 0.;
  /* #1: @1 = zeros(1x8) */
  casadi_clear(w1, 8);
  /* #2: @2 = 0.5 */
  w2 = 5.0000000000000000e-01;
  /* #3: @3 = all_2.22045e-16(3x1) */
  casadi_fill(w3, 3, 2.2204460492503131e-16);
  /* #4: @4 = zeros(8x1) */
  casadi_clear(w4, 8);
  /* #5: @5 = input[3][0] */
  casadi_copy(arg[3], 18, w5);
  /* #6: @6 = @5[0] */
  for (rr=(&w6), ss=w5+0; ss!=w5+1; ss+=1) *rr++ = *ss;
  /* #7: @7 = @5[1] */
  for (rr=(&w7), ss=w5+1; ss!=w5+2; ss+=1) *rr++ = *ss;
  /* #8: @8 = @5[2] */
  for (rr=(&w8), ss=w5+2; ss!=w5+3; ss+=1) *rr++ = *ss;
  /* #9: @9 = @5[3] */
  for (rr=(&w9), ss=w5+3; ss!=w5+4; ss+=1) *rr++ = *ss;
  /* #10: @10 = horzcat(@6, @7, @8, @9) */
  rr=w10;
  *rr++ = w6;
  *rr++ = w7;
  *rr++ = w8;
  *rr++ = w9;
  /* #11: @10 = @10' */
  /* #12: @11 = (-@7) */
  w11 = (- w7 );
  /* #13: @12 = (-@8) */
  w12 = (- w8 );
  /* #14: @13 = horzcat(@11, @6, @9, @12) */
  rr=w13;
  *rr++ = w11;
  *rr++ = w6;
  *rr++ = w9;
  *rr++ = w12;
  /* #15: @13 = @13' */
  /* #16: @9 = (-@9) */
  w9 = (- w9 );
  /* #17: @14 = horzcat(@12, @9, @6, @7) */
  rr=w14;
  *rr++ = w12;
  *rr++ = w9;
  *rr++ = w6;
  *rr++ = w7;
  /* #18: @14 = @14' */
  /* #19: @15 = horzcat(@9, @8, @11, @6) */
  rr=w15;
  *rr++ = w9;
  *rr++ = w8;
  *rr++ = w11;
  *rr++ = w6;
  /* #20: @15 = @15' */
  /* #21: @16 = horzcat(@10, @13, @14, @15) */
  rr=w16;
  for (i=0, cs=w10; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w13; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w14; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w15; i<4; ++i) *rr++ = *cs++;
  /* #22: @17 = @16' */
  for (i=0, rr=w17, cs=w16; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #23: @16 = zeros(4x4) */
  casadi_clear(w16, 16);
  /* #24: @18 = horzcat(@17, @16) */
  rr=w18;
  for (i=0, cs=w17; i<16; ++i) *rr++ = *cs++;
  for (i=0, cs=w16; i<16; ++i) *rr++ = *cs++;
  /* #25: @19 = @18' */
  for (i=0, rr=w19, cs=w18; i<8; ++i) for (j=0; j<4; ++j) rr[i+j*8] = *cs++;
  /* #26: @9 = @5[4] */
  for (rr=(&w9), ss=w5+4; ss!=w5+5; ss+=1) *rr++ = *ss;
  /* #27: @8 = @5[5] */
  for (rr=(&w8), ss=w5+5; ss!=w5+6; ss+=1) *rr++ = *ss;
  /* #28: @11 = @5[6] */
  for (rr=(&w11), ss=w5+6; ss!=w5+7; ss+=1) *rr++ = *ss;
  /* #29: @6 = @5[7] */
  for (rr=(&w6), ss=w5+7; ss!=w5+8; ss+=1) *rr++ = *ss;
  /* #30: @10 = horzcat(@9, @8, @11, @6) */
  rr=w10;
  *rr++ = w9;
  *rr++ = w8;
  *rr++ = w11;
  *rr++ = w6;
  /* #31: @10 = @10' */
  /* #32: @12 = (-@8) */
  w12 = (- w8 );
  /* #33: @7 = (-@11) */
  w7 = (- w11 );
  /* #34: @13 = horzcat(@12, @9, @6, @7) */
  rr=w13;
  *rr++ = w12;
  *rr++ = w9;
  *rr++ = w6;
  *rr++ = w7;
  /* #35: @13 = @13' */
  /* #36: @6 = (-@6) */
  w6 = (- w6 );
  /* #37: @14 = horzcat(@7, @6, @9, @8) */
  rr=w14;
  *rr++ = w7;
  *rr++ = w6;
  *rr++ = w9;
  *rr++ = w8;
  /* #38: @14 = @14' */
  /* #39: @15 = horzcat(@6, @11, @12, @9) */
  rr=w15;
  *rr++ = w6;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w9;
  /* #40: @15 = @15' */
  /* #41: @20 = horzcat(@10, @13, @14, @15) */
  rr=w20;
  for (i=0, cs=w10; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w13; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w14; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w15; i<4; ++i) *rr++ = *cs++;
  /* #42: @21 = @20' */
  for (i=0, rr=w21, cs=w20; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #43: @18 = horzcat(@21, @17) */
  rr=w18;
  for (i=0, cs=w21; i<16; ++i) *rr++ = *cs++;
  for (i=0, cs=w17; i<16; ++i) *rr++ = *cs++;
  /* #44: @22 = @18' */
  for (i=0, rr=w22, cs=w18; i<8; ++i) for (j=0; j<4; ++j) rr[i+j*8] = *cs++;
  /* #45: @23 = horzcat(@19, @22) */
  rr=w23;
  for (i=0, cs=w19; i<32; ++i) *rr++ = *cs++;
  for (i=0, cs=w22; i<32; ++i) *rr++ = *cs++;
  /* #46: @24 = @23' */
  for (i=0, rr=w24, cs=w23; i<8; ++i) for (j=0; j<8; ++j) rr[i+j*8] = *cs++;
  /* #47: @6 = input[0][0] */
  w6 = arg[0] ? arg[0][0] : 0;
  /* #48: @11 = input[0][1] */
  w11 = arg[0] ? arg[0][1] : 0;
  /* #49: @12 = input[0][2] */
  w12 = arg[0] ? arg[0][2] : 0;
  /* #50: @9 = input[0][3] */
  w9 = arg[0] ? arg[0][3] : 0;
  /* #51: @7 = input[0][4] */
  w7 = arg[0] ? arg[0][4] : 0;
  /* #52: @8 = input[0][5] */
  w8 = arg[0] ? arg[0][5] : 0;
  /* #53: @25 = input[0][6] */
  w25 = arg[0] ? arg[0][6] : 0;
  /* #54: @26 = input[0][7] */
  w26 = arg[0] ? arg[0][7] : 0;
  /* #55: @27 = input[0][8] */
  w27 = arg[0] ? arg[0][8] : 0;
  /* #56: @28 = input[0][9] */
  w28 = arg[0] ? arg[0][9] : 0;
  /* #57: @29 = input[0][10] */
  w29 = arg[0] ? arg[0][10] : 0;
  /* #58: @30 = input[0][11] */
  w30 = arg[0] ? arg[0][11] : 0;
  /* #59: @31 = input[0][12] */
  w31 = arg[0] ? arg[0][12] : 0;
  /* #60: @32 = input[0][13] */
  w32 = arg[0] ? arg[0][13] : 0;
  /* #61: @33 = vertcat(@6, @11, @12, @9, @7, @8, @25, @26, @27, @28, @29, @30, @31, @32) */
  rr=w33;
  *rr++ = w6;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w9;
  *rr++ = w7;
  *rr++ = w8;
  *rr++ = w25;
  *rr++ = w26;
  *rr++ = w27;
  *rr++ = w28;
  *rr++ = w29;
  *rr++ = w30;
  *rr++ = w31;
  *rr++ = w32;
  /* #62: @34 = @33[:8] */
  for (rr=w34, ss=w33+0; ss!=w33+8; ss+=1) *rr++ = *ss;
  /* #63: @35 = mac(@24,@34,@4) */
  casadi_copy(w4, 8, w35);
  for (i=0, rr=w35; i<1; ++i) for (j=0; j<8; ++j, ++rr) for (k=0, ss=w24+j, tt=w34+i*8; k<8; ++k) *rr += ss[k*8]**tt++;
  /* #64: @36 = @35[1:4] */
  for (rr=w36, ss=w35+1; ss!=w35+4; ss+=1) *rr++ = *ss;
  /* #65: @3 = (@3+@36) */
  for (i=0, rr=w3, cs=w36; i<3; ++i) (*rr++) += (*cs++);
  /* #66: @6 = ||@3||_F */
  w6 = sqrt(casadi_dot(3, w3, w3));
  /* #67: @11 = @35[0] */
  for (rr=(&w11), ss=w35+0; ss!=w35+1; ss+=1) *rr++ = *ss;
  /* #68: @12 = atan2(@6,@11) */
  w12  = atan2(w6,w11);
  /* #69: @12 = (2.*@12) */
  w12 = (2.* w12 );
  /* #70: @12 = (@2*@12) */
  w12  = (w2*w12);
  /* #71: @9 = @35[1] */
  for (rr=(&w9), ss=w35+1; ss!=w35+2; ss+=1) *rr++ = *ss;
  /* #72: @7 = (@12*@9) */
  w7  = (w12*w9);
  /* #73: @7 = (@7/@6) */
  w7 /= w6;
  /* #74: @8 = @35[2] */
  for (rr=(&w8), ss=w35+2; ss!=w35+3; ss+=1) *rr++ = *ss;
  /* #75: @25 = (@12*@8) */
  w25  = (w12*w8);
  /* #76: @25 = (@25/@6) */
  w25 /= w6;
  /* #77: @26 = @35[3] */
  for (rr=(&w26), ss=w35+3; ss!=w35+4; ss+=1) *rr++ = *ss;
  /* #78: @27 = (@12*@26) */
  w27  = (w12*w26);
  /* #79: @27 = (@27/@6) */
  w27 /= w6;
  /* #80: @10 = zeros(4x1) */
  casadi_clear(w10, 4);
  /* #81: @28 = @35[4] */
  for (rr=(&w28), ss=w35+4; ss!=w35+5; ss+=1) *rr++ = *ss;
  /* #82: @29 = @35[5] */
  for (rr=(&w29), ss=w35+5; ss!=w35+6; ss+=1) *rr++ = *ss;
  /* #83: @30 = (-@29) */
  w30 = (- w29 );
  /* #84: @31 = @35[6] */
  for (rr=(&w31), ss=w35+6; ss!=w35+7; ss+=1) *rr++ = *ss;
  /* #85: @32 = (-@31) */
  w32 = (- w31 );
  /* #86: @37 = @35[7] */
  for (rr=(&w37), ss=w35+7; ss!=w35+8; ss+=1) *rr++ = *ss;
  /* #87: @38 = (-@37) */
  w38 = (- w37 );
  /* #88: @13 = horzcat(@28, @30, @32, @38) */
  rr=w13;
  *rr++ = w28;
  *rr++ = w30;
  *rr++ = w32;
  *rr++ = w38;
  /* #89: @13 = @13' */
  /* #90: @14 = horzcat(@29, @28, @38, @31) */
  rr=w14;
  *rr++ = w29;
  *rr++ = w28;
  *rr++ = w38;
  *rr++ = w31;
  /* #91: @14 = @14' */
  /* #92: @15 = horzcat(@31, @37, @28, @30) */
  rr=w15;
  *rr++ = w31;
  *rr++ = w37;
  *rr++ = w28;
  *rr++ = w30;
  /* #93: @15 = @15' */
  /* #94: @39 = horzcat(@37, @32, @29, @28) */
  rr=w39;
  *rr++ = w37;
  *rr++ = w32;
  *rr++ = w29;
  *rr++ = w28;
  /* #95: @39 = @39' */
  /* #96: @21 = horzcat(@13, @14, @15, @39) */
  rr=w21;
  for (i=0, cs=w13; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w14; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w15; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w39; i<4; ++i) *rr++ = *cs++;
  /* #97: @17 = @21' */
  for (i=0, rr=w17, cs=w21; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #98: @17 = (2.*@17) */
  for (i=0, rr=w17, cs=w17; i<16; ++i) *rr++ = (2.* *cs++ );
  /* #99: @37 = (-@9) */
  w37 = (- w9 );
  /* #100: @32 = (-@8) */
  w32 = (- w8 );
  /* #101: @29 = (-@26) */
  w29 = (- w26 );
  /* #102: @13 = vertcat(@11, @37, @32, @29) */
  rr=w13;
  *rr++ = w11;
  *rr++ = w37;
  *rr++ = w32;
  *rr++ = w29;
  /* #103: @14 = mac(@17,@13,@10) */
  casadi_copy(w10, 4, w14);
  for (i=0, rr=w14; i<1; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w17+j, tt=w13+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #104: @37 = @14[1] */
  for (rr=(&w37), ss=w14+1; ss!=w14+2; ss+=1) *rr++ = *ss;
  /* #105: @37 = (@2*@37) */
  w37  = (w2*w37);
  /* #106: @32 = @14[2] */
  for (rr=(&w32), ss=w14+2; ss!=w14+3; ss+=1) *rr++ = *ss;
  /* #107: @32 = (@2*@32) */
  w32  = (w2*w32);
  /* #108: @29 = @14[3] */
  for (rr=(&w29), ss=w14+3; ss!=w14+4; ss+=1) *rr++ = *ss;
  /* #109: @29 = (@2*@29) */
  w29  = (w2*w29);
  /* #110: @35 = vertcat(@0, @7, @25, @27, @0, @37, @32, @29) */
  rr=w35;
  *rr++ = w0;
  *rr++ = w7;
  *rr++ = w25;
  *rr++ = w27;
  *rr++ = w0;
  *rr++ = w37;
  *rr++ = w32;
  *rr++ = w29;
  /* #111: @34 = @35' */
  casadi_copy(w35, 8, w34);
  /* #112: @24 = zeros(8x8) */
  casadi_clear(w24, 64);
  /* #113: @19 = input[3][1] */
  casadi_copy(arg[3] ? arg[3]+18 : 0, 32, w19);
  /* #114: @37 = @19[7] */
  for (rr=(&w37), ss=w19+7; ss!=w19+8; ss+=1) *rr++ = *ss;
  /* #115: (@24[0] = @37) */
  for (rr=w24+0, ss=(&w37); rr!=w24+1; rr+=1) *rr = *ss++;
  /* #116: @37 = @19[8] */
  for (rr=(&w37), ss=w19+8; ss!=w19+9; ss+=1) *rr++ = *ss;
  /* #117: (@24[9] = @37) */
  for (rr=w24+9, ss=(&w37); rr!=w24+10; rr+=1) *rr = *ss++;
  /* #118: @37 = @19[9] */
  for (rr=(&w37), ss=w19+9; ss!=w19+10; ss+=1) *rr++ = *ss;
  /* #119: (@24[18] = @37) */
  for (rr=w24+18, ss=(&w37); rr!=w24+19; rr+=1) *rr = *ss++;
  /* #120: @37 = @19[10] */
  for (rr=(&w37), ss=w19+10; ss!=w19+11; ss+=1) *rr++ = *ss;
  /* #121: (@24[27] = @37) */
  for (rr=w24+27, ss=(&w37); rr!=w24+28; rr+=1) *rr = *ss++;
  /* #122: @37 = @19[0] */
  for (rr=(&w37), ss=w19+0; ss!=w19+1; ss+=1) *rr++ = *ss;
  /* #123: (@24[36] = @37) */
  for (rr=w24+36, ss=(&w37); rr!=w24+37; rr+=1) *rr = *ss++;
  /* #124: @37 = @19[1] */
  for (rr=(&w37), ss=w19+1; ss!=w19+2; ss+=1) *rr++ = *ss;
  /* #125: (@24[45] = @37) */
  for (rr=w24+45, ss=(&w37); rr!=w24+46; rr+=1) *rr = *ss++;
  /* #126: @37 = @19[2] */
  for (rr=(&w37), ss=w19+2; ss!=w19+3; ss+=1) *rr++ = *ss;
  /* #127: (@24[54] = @37) */
  for (rr=w24+54, ss=(&w37); rr!=w24+55; rr+=1) *rr = *ss++;
  /* #128: @37 = @19[3] */
  for (rr=(&w37), ss=w19+3; ss!=w19+4; ss+=1) *rr++ = *ss;
  /* #129: (@24[63] = @37) */
  for (rr=w24+63, ss=(&w37); rr!=w24+64; rr+=1) *rr = *ss++;
  /* #130: @40 = mac(@34,@24,@1) */
  casadi_copy(w1, 8, w40);
  for (i=0, rr=w40; i<8; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w34+j, tt=w24+i*8; k<8; ++k) *rr += ss[k*1]**tt++;
  /* #131: @37 = mac(@40,@35,@0) */
  casadi_copy((&w0), 1, (&w37));
  for (i=0, rr=(&w37); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w40+j, tt=w35+i*8; k<8; ++k) *rr += ss[k*1]**tt++;
  /* #132: @14 = zeros(1x4) */
  casadi_clear(w14, 4);
  /* #133: @15 = @5[14:18] */
  for (rr=w15, ss=w5+14; ss!=w5+18; ss+=1) *rr++ = *ss;
  /* #134: @32 = input[1][0] */
  w32 = arg[1] ? arg[1][0] : 0;
  /* #135: @29 = input[1][1] */
  w29 = arg[1] ? arg[1][1] : 0;
  /* #136: @28 = input[1][2] */
  w28 = arg[1] ? arg[1][2] : 0;
  /* #137: @31 = input[1][3] */
  w31 = arg[1] ? arg[1][3] : 0;
  /* #138: @39 = vertcat(@32, @29, @28, @31) */
  rr=w39;
  *rr++ = w32;
  *rr++ = w29;
  *rr++ = w28;
  *rr++ = w31;
  /* #139: @15 = (@15-@39) */
  for (i=0, rr=w15, cs=w39; i<4; ++i) (*rr++) -= (*cs++);
  /* #140: @39 = @15' */
  casadi_copy(w15, 4, w39);
  /* #141: @41 = @19[28:32] */
  for (rr=w41, ss=w19+28; ss!=w19+32; ss+=1) *rr++ = *ss;
  /* #142: @32 = @19[28] */
  for (rr=(&w32), ss=w19+28; ss!=w19+29; ss+=1) *rr++ = *ss;
  /* #143: @29 = 62 */
  w29 = 62.;
  /* #144: @32 = (@32/@29) */
  w32 /= w29;
  /* #145: (@41[0] = @32) */
  for (rr=w41+0, ss=(&w32); rr!=w41+1; rr+=1) *rr = *ss++;
  /* #146: @32 = @41[1] */
  for (rr=(&w32), ss=w41+1; ss!=w41+2; ss+=1) *rr++ = *ss;
  /* #147: @29 = 0.35 */
  w29 = 3.4999999999999998e-01;
  /* #148: @32 = (@32/@29) */
  w32 /= w29;
  /* #149: (@41[1] = @32) */
  for (rr=w41+1, ss=(&w32); rr!=w41+2; rr+=1) *rr = *ss++;
  /* #150: @32 = @41[2] */
  for (rr=(&w32), ss=w41+2; ss!=w41+3; ss+=1) *rr++ = *ss;
  /* #151: @32 = (@32/@29) */
  w32 /= w29;
  /* #152: (@41[2] = @32) */
  for (rr=w41+2, ss=(&w32); rr!=w41+3; rr+=1) *rr = *ss++;
  /* #153: @32 = @41[3] */
  for (rr=(&w32), ss=w41+3; ss!=w41+4; ss+=1) *rr++ = *ss;
  /* #154: @32 = (@32/@29) */
  w32 /= w29;
  /* #155: (@41[3] = @32) */
  for (rr=w41+3, ss=(&w32); rr!=w41+4; rr+=1) *rr = *ss++;
  /* #156: @32 = @41[0] */
  for (rr=(&w32), ss=w41+0; ss!=w41+1; ss+=1) *rr++ = *ss;
  /* #157: @21 = @16; (@21[0] = @32) */
  casadi_copy(w16, 16, w21);
  for (rr=w21+0, ss=(&w32); rr!=w21+1; rr+=1) *rr = *ss++;
  /* #158: @32 = @41[1] */
  for (rr=(&w32), ss=w41+1; ss!=w41+2; ss+=1) *rr++ = *ss;
  /* #159: (@21[5] = @32) */
  for (rr=w21+5, ss=(&w32); rr!=w21+6; rr+=1) *rr = *ss++;
  /* #160: @32 = @41[2] */
  for (rr=(&w32), ss=w41+2; ss!=w41+3; ss+=1) *rr++ = *ss;
  /* #161: (@21[10] = @32) */
  for (rr=w21+10, ss=(&w32); rr!=w21+11; rr+=1) *rr = *ss++;
  /* #162: @32 = @41[3] */
  for (rr=(&w32), ss=w41+3; ss!=w41+4; ss+=1) *rr++ = *ss;
  /* #163: (@21[15] = @32) */
  for (rr=w21+15, ss=(&w32); rr!=w21+16; rr+=1) *rr = *ss++;
  /* #164: @41 = mac(@39,@21,@14) */
  casadi_copy(w14, 4, w41);
  for (i=0, rr=w41; i<4; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w39+j, tt=w21+i*4; k<4; ++k) *rr += ss[k*1]**tt++;
  /* #165: @32 = mac(@41,@15,@0) */
  casadi_copy((&w0), 1, (&w32));
  for (i=0, rr=(&w32); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w41+j, tt=w15+i*4; k<4; ++k) *rr += ss[k*1]**tt++;
  /* #166: @37 = (@37+@32) */
  w37 += w32;
  /* #167: @36 = zeros(1x3) */
  casadi_clear(w36, 3);
  /* #168: @42 = @33[11:14] */
  for (rr=w42, ss=w33+11; ss!=w33+14; ss+=1) *rr++ = *ss;
  /* #169: @43 = @5[11:14] */
  for (rr=w43, ss=w5+11; ss!=w5+14; ss+=1) *rr++ = *ss;
  /* #170: @42 = (@42-@43) */
  for (i=0, rr=w42, cs=w43; i<3; ++i) (*rr++) -= (*cs++);
  /* #171: @43 = @42' */
  casadi_copy(w42, 3, w43);
  /* #172: @44 = zeros(3x3) */
  casadi_clear(w44, 9);
  /* #173: @32 = @19[4] */
  for (rr=(&w32), ss=w19+4; ss!=w19+5; ss+=1) *rr++ = *ss;
  /* #174: @45 = @44; (@45[0] = @32) */
  casadi_copy(w44, 9, w45);
  for (rr=w45+0, ss=(&w32); rr!=w45+1; rr+=1) *rr = *ss++;
  /* #175: @32 = @19[5] */
  for (rr=(&w32), ss=w19+5; ss!=w19+6; ss+=1) *rr++ = *ss;
  /* #176: (@45[4] = @32) */
  for (rr=w45+4, ss=(&w32); rr!=w45+5; rr+=1) *rr = *ss++;
  /* #177: @32 = @19[6] */
  for (rr=(&w32), ss=w19+6; ss!=w19+7; ss+=1) *rr++ = *ss;
  /* #178: (@45[8] = @32) */
  for (rr=w45+8, ss=(&w32); rr!=w45+9; rr+=1) *rr = *ss++;
  /* #179: @46 = mac(@43,@45,@36) */
  casadi_copy(w36, 3, w46);
  for (i=0, rr=w46; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w43+j, tt=w45+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #180: @32 = mac(@46,@42,@0) */
  casadi_copy((&w0), 1, (&w32));
  for (i=0, rr=(&w32); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w46+j, tt=w42+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #181: @37 = (@37+@32) */
  w37 += w32;
  /* #182: @42 = @33[8:11] */
  for (rr=w42, ss=w33+8; ss!=w33+11; ss+=1) *rr++ = *ss;
  /* #183: @47 = @5[8:11] */
  for (rr=w47, ss=w5+8; ss!=w5+11; ss+=1) *rr++ = *ss;
  /* #184: @42 = (@42-@47) */
  for (i=0, rr=w42, cs=w47; i<3; ++i) (*rr++) -= (*cs++);
  /* #185: @47 = @42' */
  casadi_copy(w42, 3, w47);
  /* #186: @32 = @19[11] */
  for (rr=(&w32), ss=w19+11; ss!=w19+12; ss+=1) *rr++ = *ss;
  /* #187: (@44[0] = @32) */
  for (rr=w44+0, ss=(&w32); rr!=w44+1; rr+=1) *rr = *ss++;
  /* #188: @32 = @19[12] */
  for (rr=(&w32), ss=w19+12; ss!=w19+13; ss+=1) *rr++ = *ss;
  /* #189: (@44[4] = @32) */
  for (rr=w44+4, ss=(&w32); rr!=w44+5; rr+=1) *rr = *ss++;
  /* #190: @32 = @19[13] */
  for (rr=(&w32), ss=w19+13; ss!=w19+14; ss+=1) *rr++ = *ss;
  /* #191: (@44[8] = @32) */
  for (rr=w44+8, ss=(&w32); rr!=w44+9; rr+=1) *rr = *ss++;
  /* #192: @48 = mac(@47,@44,@36) */
  casadi_copy(w36, 3, w48);
  for (i=0, rr=w48; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w47+j, tt=w44+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #193: @0 = mac(@48,@42,@0) */
  for (i=0, rr=(&w0); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w48+j, tt=w42+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #194: @37 = (@37+@0) */
  w37 += w0;
  /* #195: output[0][0] = @37 */
  if (res[0]) res[0][0] = w37;
  /* #196: @41 = @41' */
  /* #197: @20 = @21' */
  for (i=0, rr=w20, cs=w21; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #198: @14 = mac(@39,@20,@14) */
  for (i=0, rr=w14; i<4; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w39+j, tt=w20+i*4; k<4; ++k) *rr += ss[k*1]**tt++;
  /* #199: @14 = @14' */
  /* #200: @41 = (@41+@14) */
  for (i=0, rr=w41, cs=w14; i<4; ++i) (*rr++) += (*cs++);
  /* #201: @41 = (-@41) */
  for (i=0, rr=w41, cs=w41; i<4; ++i) *rr++ = (- *cs++ );
  /* #202: {@37, @0, @32, @29} = vertsplit(@41) */
  w37 = w41[0];
  w0 = w41[1];
  w32 = w41[2];
  w29 = w41[3];
  /* #203: output[1][0] = @37 */
  if (res[1]) res[1][0] = w37;
  /* #204: output[1][1] = @0 */
  if (res[1]) res[1][1] = w0;
  /* #205: output[1][2] = @32 */
  if (res[1]) res[1][2] = w32;
  /* #206: output[1][3] = @29 */
  if (res[1]) res[1][3] = w29;
  /* #207: @33 = zeros(14x1) */
  casadi_clear(w33, 14);
  /* #208: @48 = @48' */
  /* #209: @49 = @44' */
  for (i=0, rr=w49, cs=w44; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #210: @42 = mac(@47,@49,@36) */
  casadi_copy(w36, 3, w42);
  for (i=0, rr=w42; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w47+j, tt=w49+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #211: @42 = @42' */
  /* #212: @48 = (@48+@42) */
  for (i=0, rr=w48, cs=w42; i<3; ++i) (*rr++) += (*cs++);
  /* #213: (@33[8:11] += @48) */
  for (rr=w33+8, ss=w48; rr!=w33+11; rr+=1) *rr += *ss++;
  /* #214: @46 = @46' */
  /* #215: @49 = @45' */
  for (i=0, rr=w49, cs=w45; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #216: @36 = mac(@43,@49,@36) */
  for (i=0, rr=w36; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w43+j, tt=w49+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #217: @36 = @36' */
  /* #218: @46 = (@46+@36) */
  for (i=0, rr=w46, cs=w36; i<3; ++i) (*rr++) += (*cs++);
  /* #219: (@33[11:14] += @46) */
  for (rr=w33+11, ss=w46; rr!=w33+14; rr+=1) *rr += *ss++;
  /* #220: @20 = @17' */
  for (i=0, rr=w20, cs=w17; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #221: @40 = @40' */
  /* #222: @50 = @24' */
  for (i=0, rr=w50, cs=w24; i<8; ++i) for (j=0; j<8; ++j) rr[i+j*8] = *cs++;
  /* #223: @1 = mac(@34,@50,@1) */
  for (i=0, rr=w1; i<8; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w34+j, tt=w50+i*8; k<8; ++k) *rr += ss[k*1]**tt++;
  /* #224: @1 = @1' */
  /* #225: @40 = (@40+@1) */
  for (i=0, rr=w40, cs=w1; i<8; ++i) (*rr++) += (*cs++);
  /* #226: {NULL, @29, @32, @0, NULL, @37, @28, @31} = vertsplit(@40) */
  w29 = w40[1];
  w32 = w40[2];
  w0 = w40[3];
  w37 = w40[5];
  w28 = w40[6];
  w31 = w40[7];
  /* #227: @31 = (@2*@31) */
  w31  = (w2*w31);
  /* #228: @41 = @10; (@41[3] += @31) */
  casadi_copy(w10, 4, w41);
  for (rr=w41+3, ss=(&w31); rr!=w41+4; rr+=1) *rr += *ss++;
  /* #229: @28 = (@2*@28) */
  w28  = (w2*w28);
  /* #230: (@41[2] += @28) */
  for (rr=w41+2, ss=(&w28); rr!=w41+3; rr+=1) *rr += *ss++;
  /* #231: @37 = (@2*@37) */
  w37  = (w2*w37);
  /* #232: (@41[1] += @37) */
  for (rr=w41+1, ss=(&w37); rr!=w41+2; rr+=1) *rr += *ss++;
  /* #233: @10 = mac(@20,@41,@10) */
  for (i=0, rr=w10; i<1; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w20+j, tt=w41+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #234: {@37, @28, @31, @30} = vertsplit(@10) */
  w37 = w10[0];
  w28 = w10[1];
  w31 = w10[2];
  w30 = w10[3];
  /* #235: @30 = (-@30) */
  w30 = (- w30 );
  /* #236: @40 = @4; (@40[3] += @30) */
  casadi_copy(w4, 8, w40);
  for (rr=w40+3, ss=(&w30); rr!=w40+4; rr+=1) *rr += *ss++;
  /* #237: @31 = (-@31) */
  w31 = (- w31 );
  /* #238: (@40[2] += @31) */
  for (rr=w40+2, ss=(&w31); rr!=w40+3; rr+=1) *rr += *ss++;
  /* #239: @28 = (-@28) */
  w28 = (- w28 );
  /* #240: (@40[1] += @28) */
  for (rr=w40+1, ss=(&w28); rr!=w40+2; rr+=1) *rr += *ss++;
  /* #241: (@40[0] += @37) */
  for (rr=w40+0, ss=(&w37); rr!=w40+1; rr+=1) *rr += *ss++;
  /* #242: @13 = @13' */
  /* #243: @16 = mac(@41,@13,@16) */
  for (i=0, rr=w16; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w41+j, tt=w13+i*1; k<1; ++k) *rr += ss[k*4]**tt++;
  /* #244: @16 = (2.*@16) */
  for (i=0, rr=w16, cs=w16; i<16; ++i) *rr++ = (2.* *cs++ );
  /* #245: @20 = @16' */
  for (i=0, rr=w20, cs=w16; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #246: {@41, @13, @10, @14} = horzsplit(@20) */
  casadi_copy(w20, 4, w41);
  casadi_copy(w20+4, 4, w13);
  casadi_copy(w20+8, 4, w10);
  casadi_copy(w20+12, 4, w14);
  /* #247: @14 = @14' */
  /* #248: {@37, @28, @31, @30} = horzsplit(@14) */
  w37 = w14[0];
  w28 = w14[1];
  w31 = w14[2];
  w30 = w14[3];
  /* #249: (@40[4] += @30) */
  for (rr=w40+4, ss=(&w30); rr!=w40+5; rr+=1) *rr += *ss++;
  /* #250: (@40[5] += @31) */
  for (rr=w40+5, ss=(&w31); rr!=w40+6; rr+=1) *rr += *ss++;
  /* #251: @28 = (-@28) */
  w28 = (- w28 );
  /* #252: (@40[6] += @28) */
  for (rr=w40+6, ss=(&w28); rr!=w40+7; rr+=1) *rr += *ss++;
  /* #253: (@40[7] += @37) */
  for (rr=w40+7, ss=(&w37); rr!=w40+8; rr+=1) *rr += *ss++;
  /* #254: @10 = @10' */
  /* #255: {@37, @28, @31, @30} = horzsplit(@10) */
  w37 = w10[0];
  w28 = w10[1];
  w31 = w10[2];
  w30 = w10[3];
  /* #256: @30 = (-@30) */
  w30 = (- w30 );
  /* #257: (@40[5] += @30) */
  for (rr=w40+5, ss=(&w30); rr!=w40+6; rr+=1) *rr += *ss++;
  /* #258: (@40[4] += @31) */
  for (rr=w40+4, ss=(&w31); rr!=w40+5; rr+=1) *rr += *ss++;
  /* #259: (@40[7] += @28) */
  for (rr=w40+7, ss=(&w28); rr!=w40+8; rr+=1) *rr += *ss++;
  /* #260: (@40[6] += @37) */
  for (rr=w40+6, ss=(&w37); rr!=w40+7; rr+=1) *rr += *ss++;
  /* #261: @13 = @13' */
  /* #262: {@37, @28, @31, @30} = horzsplit(@13) */
  w37 = w13[0];
  w28 = w13[1];
  w31 = w13[2];
  w30 = w13[3];
  /* #263: (@40[6] += @30) */
  for (rr=w40+6, ss=(&w30); rr!=w40+7; rr+=1) *rr += *ss++;
  /* #264: @31 = (-@31) */
  w31 = (- w31 );
  /* #265: (@40[7] += @31) */
  for (rr=w40+7, ss=(&w31); rr!=w40+8; rr+=1) *rr += *ss++;
  /* #266: (@40[4] += @28) */
  for (rr=w40+4, ss=(&w28); rr!=w40+5; rr+=1) *rr += *ss++;
  /* #267: (@40[5] += @37) */
  for (rr=w40+5, ss=(&w37); rr!=w40+6; rr+=1) *rr += *ss++;
  /* #268: @41 = @41' */
  /* #269: {@37, @28, @31, @30} = horzsplit(@41) */
  w37 = w41[0];
  w28 = w41[1];
  w31 = w41[2];
  w30 = w41[3];
  /* #270: @30 = (-@30) */
  w30 = (- w30 );
  /* #271: (@40[7] += @30) */
  for (rr=w40+7, ss=(&w30); rr!=w40+8; rr+=1) *rr += *ss++;
  /* #272: @31 = (-@31) */
  w31 = (- w31 );
  /* #273: (@40[6] += @31) */
  for (rr=w40+6, ss=(&w31); rr!=w40+7; rr+=1) *rr += *ss++;
  /* #274: @28 = (-@28) */
  w28 = (- w28 );
  /* #275: (@40[5] += @28) */
  for (rr=w40+5, ss=(&w28); rr!=w40+6; rr+=1) *rr += *ss++;
  /* #276: (@40[4] += @37) */
  for (rr=w40+4, ss=(&w37); rr!=w40+5; rr+=1) *rr += *ss++;
  /* #277: @37 = (@0/@6) */
  w37  = (w0/w6);
  /* #278: @28 = (@12*@37) */
  w28  = (w12*w37);
  /* #279: (@40[3] += @28) */
  for (rr=w40+3, ss=(&w28); rr!=w40+4; rr+=1) *rr += *ss++;
  /* #280: @28 = (@32/@6) */
  w28  = (w32/w6);
  /* #281: @31 = (@12*@28) */
  w31  = (w12*w28);
  /* #282: (@40[2] += @31) */
  for (rr=w40+2, ss=(&w31); rr!=w40+3; rr+=1) *rr += *ss++;
  /* #283: @31 = (@29/@6) */
  w31  = (w29/w6);
  /* #284: @12 = (@12*@31) */
  w12 *= w31;
  /* #285: (@40[1] += @12) */
  for (rr=w40+1, ss=(&w12); rr!=w40+2; rr+=1) *rr += *ss++;
  /* #286: @12 = sq(@6) */
  w12 = casadi_sq( w6 );
  /* #287: @30 = sq(@11) */
  w30 = casadi_sq( w11 );
  /* #288: @12 = (@12+@30) */
  w12 += w30;
  /* #289: @30 = (@6/@12) */
  w30  = (w6/w12);
  /* #290: @26 = (@26*@37) */
  w26 *= w37;
  /* #291: @26 = (@2*@26) */
  w26  = (w2*w26);
  /* #292: @8 = (@8*@28) */
  w8 *= w28;
  /* #293: @8 = (@2*@8) */
  w8  = (w2*w8);
  /* #294: @26 = (@26+@8) */
  w26 += w8;
  /* #295: @9 = (@9*@31) */
  w9 *= w31;
  /* #296: @2 = (@2*@9) */
  w2 *= w9;
  /* #297: @26 = (@26+@2) */
  w26 += w2;
  /* #298: @26 = (2.*@26) */
  w26 = (2.* w26 );
  /* #299: @30 = (@30*@26) */
  w30 *= w26;
  /* #300: @30 = (-@30) */
  w30 = (- w30 );
  /* #301: (@40[0] += @30) */
  for (rr=w40+0, ss=(&w30); rr!=w40+1; rr+=1) *rr += *ss++;
  /* #302: @25 = (@25/@6) */
  w25 /= w6;
  /* #303: @25 = (@25*@32) */
  w25 *= w32;
  /* #304: @25 = (-@25) */
  w25 = (- w25 );
  /* #305: @27 = (@27/@6) */
  w27 /= w6;
  /* #306: @27 = (@27*@0) */
  w27 *= w0;
  /* #307: @25 = (@25-@27) */
  w25 -= w27;
  /* #308: @7 = (@7/@6) */
  w7 /= w6;
  /* #309: @7 = (@7*@29) */
  w7 *= w29;
  /* #310: @25 = (@25-@7) */
  w25 -= w7;
  /* #311: @11 = (@11/@12) */
  w11 /= w12;
  /* #312: @11 = (@11*@26) */
  w11 *= w26;
  /* #313: @25 = (@25+@11) */
  w25 += w11;
  /* #314: @25 = (@25/@6) */
  w25 /= w6;
  /* #315: @3 = (@25*@3) */
  for (i=0, rr=w3, cs=w3; i<3; ++i) (*rr++)  = (w25*(*cs++));
  /* #316: (@40[1:4] += @3) */
  for (rr=w40+1, ss=w3; rr!=w40+4; rr+=1) *rr += *ss++;
  /* #317: @4 = mac(@23,@40,@4) */
  for (i=0, rr=w4; i<1; ++i) for (j=0; j<8; ++j, ++rr) for (k=0, ss=w23+j, tt=w40+i*8; k<8; ++k) *rr += ss[k*8]**tt++;
  /* #318: (@33[:8] += @4) */
  for (rr=w33+0, ss=w4; rr!=w33+8; rr+=1) *rr += *ss++;
  /* #319: {@25, @6, @11, @26, @12, @7, @29, @27, @0, @32, @30, @2, @9, @31} = vertsplit(@33) */
  w25 = w33[0];
  w6 = w33[1];
  w11 = w33[2];
  w26 = w33[3];
  w12 = w33[4];
  w7 = w33[5];
  w29 = w33[6];
  w27 = w33[7];
  w0 = w33[8];
  w32 = w33[9];
  w30 = w33[10];
  w2 = w33[11];
  w9 = w33[12];
  w31 = w33[13];
  /* #320: output[1][4] = @25 */
  if (res[1]) res[1][4] = w25;
  /* #321: output[1][5] = @6 */
  if (res[1]) res[1][5] = w6;
  /* #322: output[1][6] = @11 */
  if (res[1]) res[1][6] = w11;
  /* #323: output[1][7] = @26 */
  if (res[1]) res[1][7] = w26;
  /* #324: output[1][8] = @12 */
  if (res[1]) res[1][8] = w12;
  /* #325: output[1][9] = @7 */
  if (res[1]) res[1][9] = w7;
  /* #326: output[1][10] = @29 */
  if (res[1]) res[1][10] = w29;
  /* #327: output[1][11] = @27 */
  if (res[1]) res[1][11] = w27;
  /* #328: output[1][12] = @0 */
  if (res[1]) res[1][12] = w0;
  /* #329: output[1][13] = @32 */
  if (res[1]) res[1][13] = w32;
  /* #330: output[1][14] = @30 */
  if (res[1]) res[1][14] = w30;
  /* #331: output[1][15] = @2 */
  if (res[1]) res[1][15] = w2;
  /* #332: output[1][16] = @9 */
  if (res[1]) res[1][16] = w9;
  /* #333: output[1][17] = @31 */
  if (res[1]) res[1][17] = w31;
  return 0;
}

CASADI_SYMBOL_EXPORT int dq_quadrotor_cost_ext_cost_0_fun_jac(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int dq_quadrotor_cost_ext_cost_0_fun_jac_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int dq_quadrotor_cost_ext_cost_0_fun_jac_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void dq_quadrotor_cost_ext_cost_0_fun_jac_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int dq_quadrotor_cost_ext_cost_0_fun_jac_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void dq_quadrotor_cost_ext_cost_0_fun_jac_release(int mem) {
}

CASADI_SYMBOL_EXPORT void dq_quadrotor_cost_ext_cost_0_fun_jac_incref(void) {
}

CASADI_SYMBOL_EXPORT void dq_quadrotor_cost_ext_cost_0_fun_jac_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int dq_quadrotor_cost_ext_cost_0_fun_jac_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int dq_quadrotor_cost_ext_cost_0_fun_jac_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real dq_quadrotor_cost_ext_cost_0_fun_jac_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* dq_quadrotor_cost_ext_cost_0_fun_jac_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* dq_quadrotor_cost_ext_cost_0_fun_jac_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* dq_quadrotor_cost_ext_cost_0_fun_jac_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* dq_quadrotor_cost_ext_cost_0_fun_jac_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s5;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int dq_quadrotor_cost_ext_cost_0_fun_jac_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 18;
  if (sz_res) *sz_res = 16;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 522;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
