/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) dq_quadrotor_impl_dae_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_c2 CASADI_PREFIX(c2)
#define casadi_c3 CASADI_PREFIX(c3)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_f2 CASADI_PREFIX(f2)
#define casadi_norm_2 CASADI_PREFIX(norm_2)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

casadi_real casadi_norm_2(casadi_int n, const casadi_real* x) {
  return sqrt(casadi_dot(n, x, x));
}

static const casadi_int casadi_s0[3] = {14, 1, 1};
static const casadi_int casadi_s1[3] = {4, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};
static const casadi_int casadi_s3[3] = {0, 0, 1};
static const casadi_int casadi_s4[3] = {50, 1, 1};

static const casadi_real casadi_c0[3] = {-2.1978939779902899e+02, -2.1978939779902899e+02, -3.5461621659958513e+02};
static const casadi_real casadi_c1[9] = 
  {4.5498099999999996e-03, 0., 0., 0., 4.5498099999999996e-03, 0., 0., 0.,
  2.8199499999999999e-03};
static const casadi_real casadi_c2[3] = {2.1978939779902899e+02, 2.1978939779902899e+02, 3.5461621659958513e+02};
static const casadi_real casadi_c3[3] = {0., 0., 1.};

/* f_quat:(i0[8])->(o0[4]) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: output[0][0] = @0 */
  if (res[0]) res[0][0] = w0;
  /* #2: @0 = input[0][1] */
  w0 = arg[0] ? arg[0][1] : 0;
  /* #3: output[0][1] = @0 */
  if (res[0]) res[0][1] = w0;
  /* #4: @0 = input[0][2] */
  w0 = arg[0] ? arg[0][2] : 0;
  /* #5: output[0][2] = @0 */
  if (res[0]) res[0][2] = w0;
  /* #6: @0 = input[0][3] */
  w0 = arg[0] ? arg[0][3] : 0;
  /* #7: output[0][3] = @0 */
  if (res[0]) res[0][3] = w0;
  return 0;
}

/* f_rot_inv:(i0[4],i1[3])->(o0[3]) */
static int casadi_f2(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *w00=w+4, *w01=w+8, *w02=w+12, w03, w04, w05, w06, *w07=w+20, w08, w09, *w10=w+26;
  casadi_real *w11=w+30, *w12=w+34, *w13=w+38, *w14=w+54, *w15=w+70;
  const casadi_real *cs, *ct;
  /* #0: @0 = zeros(4x1) */
  casadi_clear(w00, 4);
  /* #1: @1 = zeros(4x1) */
  casadi_clear(w01, 4);
  /* #2: @2 = input[0][0] */
  casadi_copy(arg[0], 4, w02);
  /* #3: @3 = @2[0] */
  for (rr=(&w03), cs=w02+0; cs!=w02+1; cs+=1) *rr++ = *cs;
  /* #4: @4 = @2[1] */
  for (rr=(&w04), cs=w02+1; cs!=w02+2; cs+=1) *rr++ = *cs;
  /* #5: @5 = @2[2] */
  for (rr=(&w05), cs=w02+2; cs!=w02+3; cs+=1) *rr++ = *cs;
  /* #6: @6 = @2[3] */
  for (rr=(&w06), cs=w02+3; cs!=w02+4; cs+=1) *rr++ = *cs;
  /* #7: @7 = horzcat(@3, @4, @5, @6) */
  rr=w07;
  *rr++ = w03;
  *rr++ = w04;
  *rr++ = w05;
  *rr++ = w06;
  /* #8: @7 = @7' */
  /* #9: @3 = (-@4) */
  w03 = (- w04 );
  /* #10: @8 = @2[0] */
  for (rr=(&w08), cs=w02+0; cs!=w02+1; cs+=1) *rr++ = *cs;
  /* #11: @9 = (-@5) */
  w09 = (- w05 );
  /* #12: @10 = horzcat(@3, @8, @6, @9) */
  rr=w10;
  *rr++ = w03;
  *rr++ = w08;
  *rr++ = w06;
  *rr++ = w09;
  /* #13: @10 = @10' */
  /* #14: @6 = (-@6) */
  w06 = (- w06 );
  /* #15: @8 = @2[0] */
  for (rr=(&w08), cs=w02+0; cs!=w02+1; cs+=1) *rr++ = *cs;
  /* #16: @11 = horzcat(@9, @6, @8, @4) */
  rr=w11;
  *rr++ = w09;
  *rr++ = w06;
  *rr++ = w08;
  *rr++ = w04;
  /* #17: @11 = @11' */
  /* #18: @9 = @2[0] */
  for (rr=(&w09), cs=w02+0; cs!=w02+1; cs+=1) *rr++ = *cs;
  /* #19: @12 = horzcat(@6, @5, @3, @9) */
  rr=w12;
  *rr++ = w06;
  *rr++ = w05;
  *rr++ = w03;
  *rr++ = w09;
  /* #20: @12 = @12' */
  /* #21: @13 = horzcat(@7, @10, @11, @12) */
  rr=w13;
  for (i=0, cs=w07; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w10; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w11; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w12; i<4; ++i) *rr++ = *cs++;
  /* #22: @14 = @13' */
  for (i=0, rr=w14, cs=w13; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #23: @6 = 0 */
  w06 = 0.;
  /* #24: @15 = input[1][0] */
  casadi_copy(arg[1], 3, w15);
  /* #25: @7 = vertcat(@6, @15) */
  rr=w07;
  *rr++ = w06;
  for (i=0, cs=w15; i<3; ++i) *rr++ = *cs++;
  /* #26: @1 = mac(@14,@7,@1) */
  for (i=0, rr=w01; i<1; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, cs=w14+j, ct=w07+i*4; k<4; ++k) *rr += cs[k*4]**ct++;
  /* #27: @6 = @1[0] */
  for (rr=(&w06), cs=w01+0; cs!=w01+1; cs+=1) *rr++ = *cs;
  /* #28: @5 = @1[1] */
  for (rr=(&w05), cs=w01+1; cs!=w01+2; cs+=1) *rr++ = *cs;
  /* #29: @5 = (-@5) */
  w05 = (- w05 );
  /* #30: @3 = @1[2] */
  for (rr=(&w03), cs=w01+2; cs!=w01+3; cs+=1) *rr++ = *cs;
  /* #31: @3 = (-@3) */
  w03 = (- w03 );
  /* #32: @9 = @1[3] */
  for (rr=(&w09), cs=w01+3; cs!=w01+4; cs+=1) *rr++ = *cs;
  /* #33: @9 = (-@9) */
  w09 = (- w09 );
  /* #34: @7 = horzcat(@6, @5, @3, @9) */
  rr=w07;
  *rr++ = w06;
  *rr++ = w05;
  *rr++ = w03;
  *rr++ = w09;
  /* #35: @7 = @7' */
  /* #36: @6 = @1[1] */
  for (rr=(&w06), cs=w01+1; cs!=w01+2; cs+=1) *rr++ = *cs;
  /* #37: @5 = @1[0] */
  for (rr=(&w05), cs=w01+0; cs!=w01+1; cs+=1) *rr++ = *cs;
  /* #38: @3 = @1[3] */
  for (rr=(&w03), cs=w01+3; cs!=w01+4; cs+=1) *rr++ = *cs;
  /* #39: @3 = (-@3) */
  w03 = (- w03 );
  /* #40: @9 = @1[2] */
  for (rr=(&w09), cs=w01+2; cs!=w01+3; cs+=1) *rr++ = *cs;
  /* #41: @10 = horzcat(@6, @5, @3, @9) */
  rr=w10;
  *rr++ = w06;
  *rr++ = w05;
  *rr++ = w03;
  *rr++ = w09;
  /* #42: @10 = @10' */
  /* #43: @6 = @1[2] */
  for (rr=(&w06), cs=w01+2; cs!=w01+3; cs+=1) *rr++ = *cs;
  /* #44: @5 = @1[3] */
  for (rr=(&w05), cs=w01+3; cs!=w01+4; cs+=1) *rr++ = *cs;
  /* #45: @3 = @1[0] */
  for (rr=(&w03), cs=w01+0; cs!=w01+1; cs+=1) *rr++ = *cs;
  /* #46: @9 = @1[1] */
  for (rr=(&w09), cs=w01+1; cs!=w01+2; cs+=1) *rr++ = *cs;
  /* #47: @9 = (-@9) */
  w09 = (- w09 );
  /* #48: @11 = horzcat(@6, @5, @3, @9) */
  rr=w11;
  *rr++ = w06;
  *rr++ = w05;
  *rr++ = w03;
  *rr++ = w09;
  /* #49: @11 = @11' */
  /* #50: @6 = @1[3] */
  for (rr=(&w06), cs=w01+3; cs!=w01+4; cs+=1) *rr++ = *cs;
  /* #51: @5 = @1[2] */
  for (rr=(&w05), cs=w01+2; cs!=w01+3; cs+=1) *rr++ = *cs;
  /* #52: @5 = (-@5) */
  w05 = (- w05 );
  /* #53: @3 = @1[1] */
  for (rr=(&w03), cs=w01+1; cs!=w01+2; cs+=1) *rr++ = *cs;
  /* #54: @9 = @1[0] */
  for (rr=(&w09), cs=w01+0; cs!=w01+1; cs+=1) *rr++ = *cs;
  /* #55: @1 = horzcat(@6, @5, @3, @9) */
  rr=w01;
  *rr++ = w06;
  *rr++ = w05;
  *rr++ = w03;
  *rr++ = w09;
  /* #56: @1 = @1' */
  /* #57: @14 = horzcat(@7, @10, @11, @1) */
  rr=w14;
  for (i=0, cs=w07; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w10; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w11; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w01; i<4; ++i) *rr++ = *cs++;
  /* #58: @13 = @14' */
  for (i=0, rr=w13, cs=w14; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #59: @0 = mac(@13,@2,@0) */
  for (i=0, rr=w00; i<1; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, cs=w13+j, ct=w02+i*4; k<4; ++k) *rr += cs[k*4]**ct++;
  /* #60: @15 = @0[1:4] */
  for (rr=w15, cs=w00+1; cs!=w00+4; cs+=1) *rr++ = *cs;
  /* #61: output[0][0] = @15 */
  casadi_copy(w15, 3, res[0]);
  return 0;
}

/* dq_quadrotor_impl_dae_fun:(i0[14],i1[14],i2[4],i3[0],i4[],i5[50])->(o0[14]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real **res1=res+1, *rr, w00, w01, w02, w03, w04, w05, w06, w07, w08, w09;
  casadi_real w10, w11, w12, w13, *w14=w+87, *w15=w+101, *w16=w+109, *w17=w+113, *w18=w+117, *w19=w+121, *w20=w+125, *w21=w+141;
  casadi_real *w22=w+157, *w23=w+189, *w24=w+221, *w25=w+237, *w26=w+269, *w27=w+333, w28, w29, *w30=w+399, *w31=w+407, *w32=w+421, *w33=w+424;
  casadi_real *w35=w+436, *w36=w+439;
  const casadi_real **arg1=arg+6, *cs, *ct, *wr34;
  /* #0: @0 = input[1][0] */
  w00 = arg[1] ? arg[1][0] : 0;
  /* #1: @1 = input[1][1] */
  w01 = arg[1] ? arg[1][1] : 0;
  /* #2: @2 = input[1][2] */
  w02 = arg[1] ? arg[1][2] : 0;
  /* #3: @3 = input[1][3] */
  w03 = arg[1] ? arg[1][3] : 0;
  /* #4: @4 = input[1][4] */
  w04 = arg[1] ? arg[1][4] : 0;
  /* #5: @5 = input[1][5] */
  w05 = arg[1] ? arg[1][5] : 0;
  /* #6: @6 = input[1][6] */
  w06 = arg[1] ? arg[1][6] : 0;
  /* #7: @7 = input[1][7] */
  w07 = arg[1] ? arg[1][7] : 0;
  /* #8: @8 = input[1][8] */
  w08 = arg[1] ? arg[1][8] : 0;
  /* #9: @9 = input[1][9] */
  w09 = arg[1] ? arg[1][9] : 0;
  /* #10: @10 = input[1][10] */
  w10 = arg[1] ? arg[1][10] : 0;
  /* #11: @11 = input[1][11] */
  w11 = arg[1] ? arg[1][11] : 0;
  /* #12: @12 = input[1][12] */
  w12 = arg[1] ? arg[1][12] : 0;
  /* #13: @13 = input[1][13] */
  w13 = arg[1] ? arg[1][13] : 0;
  /* #14: @14 = vertcat(@0, @1, @2, @3, @4, @5, @6, @7, @8, @9, @10, @11, @12, @13) */
  rr=w14;
  *rr++ = w00;
  *rr++ = w01;
  *rr++ = w02;
  *rr++ = w03;
  *rr++ = w04;
  *rr++ = w05;
  *rr++ = w06;
  *rr++ = w07;
  *rr++ = w08;
  *rr++ = w09;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  /* #15: @0 = 0.5 */
  w00 = 5.0000000000000000e-01;
  /* #16: @15 = zeros(8x1) */
  casadi_clear(w15, 8);
  /* #17: @1 = input[0][0] */
  w01 = arg[0] ? arg[0][0] : 0;
  /* #18: @2 = input[0][1] */
  w02 = arg[0] ? arg[0][1] : 0;
  /* #19: @3 = (-@2) */
  w03 = (- w02 );
  /* #20: @4 = input[0][2] */
  w04 = arg[0] ? arg[0][2] : 0;
  /* #21: @5 = (-@4) */
  w05 = (- w04 );
  /* #22: @6 = input[0][3] */
  w06 = arg[0] ? arg[0][3] : 0;
  /* #23: @7 = (-@6) */
  w07 = (- w06 );
  /* #24: @16 = horzcat(@1, @3, @5, @7) */
  rr=w16;
  *rr++ = w01;
  *rr++ = w03;
  *rr++ = w05;
  *rr++ = w07;
  /* #25: @16 = @16' */
  /* #26: @17 = horzcat(@2, @1, @7, @4) */
  rr=w17;
  *rr++ = w02;
  *rr++ = w01;
  *rr++ = w07;
  *rr++ = w04;
  /* #27: @17 = @17' */
  /* #28: @18 = horzcat(@4, @6, @1, @3) */
  rr=w18;
  *rr++ = w04;
  *rr++ = w06;
  *rr++ = w01;
  *rr++ = w03;
  /* #29: @18 = @18' */
  /* #30: @19 = horzcat(@6, @5, @2, @1) */
  rr=w19;
  *rr++ = w06;
  *rr++ = w05;
  *rr++ = w02;
  *rr++ = w01;
  /* #31: @19 = @19' */
  /* #32: @20 = horzcat(@16, @17, @18, @19) */
  rr=w20;
  for (i=0, cs=w16; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w17; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w18; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w19; i<4; ++i) *rr++ = *cs++;
  /* #33: @21 = @20' */
  for (i=0, rr=w21, cs=w20; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #34: @20 = zeros(4x4) */
  casadi_clear(w20, 16);
  /* #35: @22 = horzcat(@21, @20) */
  rr=w22;
  for (i=0, cs=w21; i<16; ++i) *rr++ = *cs++;
  for (i=0, cs=w20; i<16; ++i) *rr++ = *cs++;
  /* #36: @23 = @22' */
  for (i=0, rr=w23, cs=w22; i<8; ++i) for (j=0; j<4; ++j) rr[i+j*8] = *cs++;
  /* #37: @5 = input[0][4] */
  w05 = arg[0] ? arg[0][4] : 0;
  /* #38: @3 = input[0][5] */
  w03 = arg[0] ? arg[0][5] : 0;
  /* #39: @7 = (-@3) */
  w07 = (- w03 );
  /* #40: @8 = input[0][6] */
  w08 = arg[0] ? arg[0][6] : 0;
  /* #41: @9 = (-@8) */
  w09 = (- w08 );
  /* #42: @10 = input[0][7] */
  w10 = arg[0] ? arg[0][7] : 0;
  /* #43: @11 = (-@10) */
  w11 = (- w10 );
  /* #44: @16 = horzcat(@5, @7, @9, @11) */
  rr=w16;
  *rr++ = w05;
  *rr++ = w07;
  *rr++ = w09;
  *rr++ = w11;
  /* #45: @16 = @16' */
  /* #46: @17 = horzcat(@3, @5, @11, @8) */
  rr=w17;
  *rr++ = w03;
  *rr++ = w05;
  *rr++ = w11;
  *rr++ = w08;
  /* #47: @17 = @17' */
  /* #48: @18 = horzcat(@8, @10, @5, @7) */
  rr=w18;
  *rr++ = w08;
  *rr++ = w10;
  *rr++ = w05;
  *rr++ = w07;
  /* #49: @18 = @18' */
  /* #50: @19 = horzcat(@10, @9, @3, @5) */
  rr=w19;
  *rr++ = w10;
  *rr++ = w09;
  *rr++ = w03;
  *rr++ = w05;
  /* #51: @19 = @19' */
  /* #52: @20 = horzcat(@16, @17, @18, @19) */
  rr=w20;
  for (i=0, cs=w16; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w17; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w18; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w19; i<4; ++i) *rr++ = *cs++;
  /* #53: @24 = @20' */
  for (i=0, rr=w24, cs=w20; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #54: @22 = horzcat(@24, @21) */
  rr=w22;
  for (i=0, cs=w24; i<16; ++i) *rr++ = *cs++;
  for (i=0, cs=w21; i<16; ++i) *rr++ = *cs++;
  /* #55: @25 = @22' */
  for (i=0, rr=w25, cs=w22; i<8; ++i) for (j=0; j<4; ++j) rr[i+j*8] = *cs++;
  /* #56: @26 = horzcat(@23, @25) */
  rr=w26;
  for (i=0, cs=w23; i<32; ++i) *rr++ = *cs++;
  for (i=0, cs=w25; i<32; ++i) *rr++ = *cs++;
  /* #57: @27 = @26' */
  for (i=0, rr=w27, cs=w26; i<8; ++i) for (j=0; j<8; ++j) rr[i+j*8] = *cs++;
  /* #58: @9 = 0 */
  w09 = 0.;
  /* #59: @7 = input[0][8] */
  w07 = arg[0] ? arg[0][8] : 0;
  /* #60: @11 = input[0][9] */
  w11 = arg[0] ? arg[0][9] : 0;
  /* #61: @12 = input[0][10] */
  w12 = arg[0] ? arg[0][10] : 0;
  /* #62: @13 = input[0][11] */
  w13 = arg[0] ? arg[0][11] : 0;
  /* #63: @28 = input[0][12] */
  w28 = arg[0] ? arg[0][12] : 0;
  /* #64: @29 = input[0][13] */
  w29 = arg[0] ? arg[0][13] : 0;
  /* #65: @30 = vertcat(@9, @7, @11, @12, @9, @13, @28, @29) */
  rr=w30;
  *rr++ = w09;
  *rr++ = w07;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w09;
  *rr++ = w13;
  *rr++ = w28;
  *rr++ = w29;
  /* #66: @15 = mac(@27,@30,@15) */
  for (i=0, rr=w15; i<1; ++i) for (j=0; j<8; ++j, ++rr) for (k=0, cs=w27+j, ct=w30+i*8; k<8; ++k) *rr += cs[k*8]**ct++;
  /* #67: @15 = (@0*@15) */
  for (i=0, rr=w15, cs=w15; i<8; ++i) (*rr++)  = (w00*(*cs++));
  /* #68: @31 = vertcat(@1, @2, @4, @6, @5, @3, @8, @10, @7, @11, @12, @13, @28, @29) */
  rr=w31;
  *rr++ = w01;
  *rr++ = w02;
  *rr++ = w04;
  *rr++ = w06;
  *rr++ = w05;
  *rr++ = w03;
  *rr++ = w08;
  *rr++ = w10;
  *rr++ = w07;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w28;
  *rr++ = w29;
  /* #69: @16 = @31[:4] */
  for (rr=w16, cs=w31+0; cs!=w31+4; cs+=1) *rr++ = *cs;
  /* #70: @1 = 10 */
  w01 = 10.;
  /* #71: @2 = 1 */
  w02 = 1.;
  /* #72: @4 = ||@16||_F */
  w04 = casadi_norm_2(4, w16);
  /* #73: @2 = (@2-@4) */
  w02 -= w04;
  /* #74: @1 = (@1*@2) */
  w01 *= w02;
  /* #75: @16 = (@16*@1) */
  for (i=0, rr=w16; i<4; ++i) (*rr++) *= w01;
  /* #76: @17 = zeros(4x1) */
  casadi_clear(w17, 4);
  /* #77: @30 = vertcat(@16, @17) */
  rr=w30;
  for (i=0, cs=w16; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w17; i<4; ++i) *rr++ = *cs++;
  /* #78: @15 = (@15+@30) */
  for (i=0, rr=w15, cs=w30; i<8; ++i) (*rr++) += (*cs++);
  /* #79: @32 = 
  [[-219.789, 00, 00], 
   [00, -219.789, 00], 
   [00, 00, -354.616]] */
  casadi_copy(casadi_c0, 3, w32);
  /* #80: @32 = nonzeros(@32) */
  /* #81: @33 = zeros(3x1) */
  casadi_clear(w33, 3);
  /* #82: @34 = 
  [[0.00454981, 0, 0], 
   [0, 0.00454981, 0], 
   [0, 0, 0.00281995]] */
  wr34 = casadi_c1;
  /* #83: @35 = @31[8:11] */
  for (rr=w35, cs=w31+8; cs!=w31+11; cs+=1) *rr++ = *cs;
  /* #84: @33 = mac(@34,@35,@33) */
  for (i=0, rr=w33; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=wr34+j, ct=w35+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #85: @1 = @33[2] */
  for (rr=(&w01), cs=w33+2; cs!=w33+3; cs+=1) *rr++ = *cs;
  /* #86: @2 = (@11*@1) */
  w02  = (w11*w01);
  /* #87: @4 = @33[1] */
  for (rr=(&w04), cs=w33+1; cs!=w33+2; cs+=1) *rr++ = *cs;
  /* #88: @6 = (@12*@4) */
  w06  = (w12*w04);
  /* #89: @2 = (@2-@6) */
  w02 -= w06;
  /* #90: @6 = @33[0] */
  for (rr=(&w06), cs=w33+0; cs!=w33+1; cs+=1) *rr++ = *cs;
  /* #91: @5 = (@12*@6) */
  w05  = (w12*w06);
  /* #92: @1 = (@7*@1) */
  w01  = (w07*w01);
  /* #93: @5 = (@5-@1) */
  w05 -= w01;
  /* #94: @4 = (@7*@4) */
  w04  = (w07*w04);
  /* #95: @6 = (@11*@6) */
  w06  = (w11*w06);
  /* #96: @4 = (@4-@6) */
  w04 -= w06;
  /* #97: @33 = vertcat(@2, @5, @4) */
  rr=w33;
  *rr++ = w02;
  *rr++ = w05;
  *rr++ = w04;
  /* #98: @32 = (@32*@33) */
  for (i=0, rr=w32, cs=w33; i<3; ++i) (*rr++) *= (*cs++);
  /* #99: @33 = 
  [[219.789, 00, 00], 
   [00, 219.789, 00], 
   [00, 00, 354.616]] */
  casadi_copy(casadi_c2, 3, w33);
  /* #100: @33 = nonzeros(@33) */
  /* #101: @2 = input[2][0] */
  w02 = arg[2] ? arg[2][0] : 0;
  /* #102: @5 = input[2][1] */
  w05 = arg[2] ? arg[2][1] : 0;
  /* #103: @4 = input[2][2] */
  w04 = arg[2] ? arg[2][2] : 0;
  /* #104: @6 = input[2][3] */
  w06 = arg[2] ? arg[2][3] : 0;
  /* #105: @16 = vertcat(@2, @5, @4, @6) */
  rr=w16;
  *rr++ = w02;
  *rr++ = w05;
  *rr++ = w04;
  *rr++ = w06;
  /* #106: @35 = @16[1:4] */
  for (rr=w35, cs=w16+1; cs!=w16+4; cs+=1) *rr++ = *cs;
  /* #107: @33 = (@33*@35) */
  for (i=0, rr=w33, cs=w35; i<3; ++i) (*rr++) *= (*cs++);
  /* #108: @32 = (@32+@33) */
  for (i=0, rr=w32, cs=w33; i<3; ++i) (*rr++) += (*cs++);
  /* #109: @5 = (@28*@12) */
  w05  = (w28*w12);
  /* #110: @4 = (@29*@11) */
  w04  = (w29*w11);
  /* #111: @5 = (@5-@4) */
  w05 -= w04;
  /* #112: @29 = (@29*@7) */
  w29 *= w07;
  /* #113: @12 = (@13*@12) */
  w12  = (w13*w12);
  /* #114: @29 = (@29-@12) */
  w29 -= w12;
  /* #115: @13 = (@13*@11) */
  w13 *= w11;
  /* #116: @28 = (@28*@7) */
  w28 *= w07;
  /* #117: @13 = (@13-@28) */
  w13 -= w28;
  /* #118: @33 = vertcat(@5, @29, @13) */
  rr=w33;
  *rr++ = w05;
  *rr++ = w29;
  *rr++ = w13;
  /* #119: @5 = 9.81 */
  w05 = 9.8100000000000005e+00;
  /* #120: @30 = @31[:8] */
  for (rr=w30, cs=w31+0; cs!=w31+8; cs+=1) *rr++ = *cs;
  /* #121: @16 = f_quat(@30) */
  arg1[0]=w30;
  res1[0]=w16;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #122: @35 = [0, 0, 1] */
  casadi_copy(casadi_c3, 3, w35);
  /* #123: @36 = f_rot_inv(@16, @35) */
  arg1[0]=w16;
  arg1[1]=w35;
  res1[0]=w36;
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #124: @36 = (@5*@36) */
  for (i=0, rr=w36, cs=w36; i<3; ++i) (*rr++)  = (w05*(*cs++));
  /* #125: @33 = (@33-@36) */
  for (i=0, rr=w33, cs=w36; i<3; ++i) (*rr++) -= (*cs++);
  /* #126: @5 = 1.08 */
  w05 = 1.0800000000000001e+00;
  /* #127: @2 = (@2/@5) */
  w02 /= w05;
  /* #128: @35 = (@35*@2) */
  for (i=0, rr=w35; i<3; ++i) (*rr++) *= w02;
  /* #129: @33 = (@33+@35) */
  for (i=0, rr=w33, cs=w35; i<3; ++i) (*rr++) += (*cs++);
  /* #130: @31 = vertcat(@15, @32, @33) */
  rr=w31;
  for (i=0, cs=w15; i<8; ++i) *rr++ = *cs++;
  for (i=0, cs=w32; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w33; i<3; ++i) *rr++ = *cs++;
  /* #131: @14 = (@14-@31) */
  for (i=0, rr=w14, cs=w31; i<14; ++i) (*rr++) -= (*cs++);
  /* #132: output[0][0] = @14 */
  casadi_copy(w14, 14, res[0]);
  return 0;
}

CASADI_SYMBOL_EXPORT int dq_quadrotor_impl_dae_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int dq_quadrotor_impl_dae_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int dq_quadrotor_impl_dae_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void dq_quadrotor_impl_dae_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int dq_quadrotor_impl_dae_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void dq_quadrotor_impl_dae_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void dq_quadrotor_impl_dae_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void dq_quadrotor_impl_dae_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int dq_quadrotor_impl_dae_fun_n_in(void) { return 6;}

CASADI_SYMBOL_EXPORT casadi_int dq_quadrotor_impl_dae_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real dq_quadrotor_impl_dae_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* dq_quadrotor_impl_dae_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* dq_quadrotor_impl_dae_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* dq_quadrotor_impl_dae_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    case 4: return casadi_s3;
    case 5: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* dq_quadrotor_impl_dae_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int dq_quadrotor_impl_dae_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 20;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 442;
  return 0;
}

CASADI_SYMBOL_EXPORT int dq_quadrotor_impl_dae_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 20*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 3*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 442*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
